### ISSUE TITLE
Allow other directories than Assets/AppCenter

### ISSUE THREAD

**Issue by monsdar** [Microsoft/AppCenter-SDK-Unity#115]
I'm working on a rather big and complex project. We're mainly trying to put Thirdparty components into a subdirectory of Assets. Today I wanted to integrate AppCenter and found that it is not working when not stored exactly in Assets/AppCenter. It would help a lot to structure bigger projects if it was possible to have AppCenter located in a different directory than the default one.

**Comment by maestersid** [comment]
@monsdar This is great feedback. I will file a request with the team. Do you think you could contact me at jawh [at] microsoft.com? We are still in the early stages preparing for a formal Unity release so I would love to learn more about your project and your needs.

**Comment by monsdar** [comment]
Thanks for the quick feedback. Yes, I can contact you about our usecases and project in general. Will also keep adding things I find in this tracker.

**Comment by annakocheshkova** [comment]
Hi @monsdar, we've just released a new version of the SDK. 
You can download new packages and try them out.

To start using AppCenter from a custom directory, change the value of `AppCenterPath` at `AppCenter/Editor/AppCenterSettingsContext`.
Note that the path **can not** be relative to this or any other file (unity has no support for this) - it must be absolute from the project root.
Also note that `Assets/Plugins/Android/res/values` will still be automatically created during Android build as it contains Android app settings.

Please keep us updated on the progress!

**Comment by monsdar** [comment]
Ok, I'll see how the new version works. Thanks for the quick update!

**Comment by annakocheshkova** [comment]
@monsdar we are going to close the issue for now, but anyway feel free to post your feedback/questions if any.
