### ISSUE TITLE
[Android] Handling Unhandled Exception on Main Thread

### ISSUE THREAD

**Issue by dkonik** [Microsoft/AppCenter-SDK-Unity#185]
https://github.com/Microsoft/AppCenter-SDK-Unity/blob/7fecca56db3d8124528f625e7e9a310279519ad5/Assets/AppCenter/Plugins/AppCenterSDK/Crashes/Shared/Crashes.cs#L308

We are seeing this take a large amount of time on the main thread on Android. Is it intentional that that is how it is handled?

**Comment by evgeny-pol** [comment]
Hello @dkonik , thank you for your feedback, we've fixed this issue so that in the next release of the Unity SDK this method will only be executed when necessary
