### ISSUE TITLE
HoloLens support

### ISSUE THREAD

**Issue by gwendalbroudinpro** [Microsoft/AppCenter-SDK-Unity#201]
Hi,

Does this support HoloLens build ?

**Comment by evgeny-pol** [comment]
Hello @gwendalbroudinpro , yes the App Center Unity SDK supports HoloLens apps

**Comment by evgeny-pol** [comment]
@gwendalbroudinpro I'm going to close this issue for now, please feel free to contact us again if you would have any other questions

**Comment by tomkrikorian** [comment]
Hi, Did anyone manage to make it work on Hololens ? Latest build isn't sending anything to the AppCenter for me/

**Comment by vladlibrestream** [comment]
Same for me. I don't see any logs  coming from Hololens 2 after adding App center SDK.
![image](https://user-images.githubusercontent.com/68757631/115926179-085f5c80-a448-11eb-95b4-ede986552765.png)

**Comment by DmitriyKirakosyan** [comment]
hi @vladlibrestream 

Thank you for reaching out to us!

Can I ask you to create a separate issue and fill out the new issue template form? Alternatively you can post the answers on those questions here.
