### ISSUE TITLE
Rename Crashes.ReportUnhandledExceptions

### ISSUE THREAD

**Issue by liortal53** [Microsoft/AppCenter-SDK-Unity#218]
I care about 2 different use cases:

- Reporting app crashes
- Reporting custom errors / exceptions (non-crashing)

The 1st use case i guess gets handled automatically after initializing the SDK (e.g: adding a GameObject with the AppCenterBehaviour componentin the scene).

As for the 2nd scenario: the name "ReportUnhandledExceptions" suggests that what this does is reporting exceptions to AppCenter, but digging into the code i could see that it actually registers to Unity's logMessageReceived event and logs any message that's an error, exception or assertion.

These are not unhandled exceptions at all, so i believe the best way would be to communicate this better to developers by renaming that method (and documentation) to reflect that.

**Comment by evgeny-pol** [comment]
Hello @liortal53 , thanks for your feedback.

By calling the `Crashes.ReportUnhandledExceptions(true)` method the SDK will also subscribe to all of the application's unhandled exceptions:
https://github.com/Microsoft/AppCenter-SDK-Unity/blob/6515991c89edd210a5a22ccce511cc4dbc4b7111/Assets/AppCenter/Plugins/AppCenterSDK/Crashes/Shared/Crashes.cs#L278

Those are pretty rare when using Unity apps as Unity usually just captures and logs all exceptions, that hasn't been manually captured (but they are still arguably the "unhandled exceptions")
The only way to cause the unhandled exception that I know is to throw an exception in the new thread like this:
https://github.com/Microsoft/AppCenter-SDK-Unity/blob/6515991c89edd210a5a22ccce511cc4dbc4b7111/Assets/Puppet/PuppetCrashes.cs#L89

Maybe you have better name for this method in mind? We will be happy to hear your opinion, but please keep in mind that this method has been officially released, so by renaming it we could break some existing applications that rely on it.

**Comment by liortal53** [comment]
There are ways of handling deprecation of methods that were already released, should not be such a big issue.

As for the naming, the method does 2 things - registers to Unity's log handler and reports asserts, errors and exceptions, while also reporting unhandled exceptions (which is less common as Unity is very limited when executing code on threads other than the scripting thread).

My suggestions would be to either split this into 2 different methods (one for unhandled exceptions, one for the unity errors), or to rename this to some other name and allow the user to select which error type he would like to report (need to consider how this will be declared, not sure yet).

In any case - the current implementation is just weird and not descriptive enough (i had to look into the code to see what it actually does, and it still didn't work BTW - see another issue reported by me).

**Comment by maestersid** [comment]
Hi @liortal53 this is good feedback. Let me look into this and see what ideas we can surface to make this more clear.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
