### ISSUE TITLE
Allow reporting custom errors to AppCenter

### ISSUE THREAD

**Issue by liortal53** [Microsoft/AppCenter-SDK-Unity#220]
I'd like to report app errors to AppCenter, even ones that do not cause a crash.

Currently this can be "hacked" by calling Crashes.TrackError, but this is not so convenient as we're not always dealing with an exception object.

The workaround is to "wrap" every message i'd like to report in an Exception object, but this is not convenient to use and simply adds unneeded overhead.

**Comment by maestersid** [comment]
Hi @liortal53. This is good feedback. If I understand correctly, these error messages are custom messaging you have thrown in your own application? Could you share a code snippet of what this call would look like in code and how it is currently managed and recorded in your application?

**Comment by liortal53** [comment]
Nothing fancy, we just have our own class that we call using an API similar to:

`LogError(string error, string extra, string stackTrace, LogType logType)`

This gets reported to the current system we report errors to.

**Comment by liortal53** [comment]
My point here was that currently there' no way of doing this, other than "wrapping" this into an exception object (create a custom exception type? use System.Exception? ) it would be nicer to be able to just log your error without this extra step.

**Comment by maestersid** [comment]
Hi @liortal53 we recently opened up a public central repository for App Center feedback. This is a good feature request for all our supported platforms, would you mind posting this suggestion as a feature request at the following link so we can get community eyes on it to also weigh in:

https://github.com/Microsoft/appcenter/issues

**Comment by liortal53** [comment]
See the issue i created. let me know if it's detailed enough.

**Comment by maestersid** [comment]
Looks great! Thank you

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
