### ISSUE TITLE
Documentation for HockeyApp transition

### ISSUE THREAD

**Issue by supersolid-corentin** [Microsoft/AppCenter-SDK-Unity#240]
Hi,

I ran into an issue with app secrets when doing the migration from HockeyApp to AppCenter. I have existing apps on HockeyApp but I want to start using the AppCenter SDK. There's no mention in the documentation that the app secret for HockeyApp is different than the one for AppCenter. It took me a while to realise that, as it's not displayed directly in AppCenter like for a new app. Could you please add some precisions in the documentation while the migration is still ongoing? Like for example that the secrets for apps still on HockeyApp can only be accessed with the 3 dots at the top right corner of the Settings page. Thanks in advance!

Otherwise, thanks for your work on the Unity SDK! It's really easier to use than the one for HockeyApp!

**Comment by maestersid** [comment]
Hi @supersolid-corentin thank you for the feedback and heads up. I will pass this feedback back to the migration team for us to revisit and make sure this information is more visible going forward.
