### ISSUE TITLE
AppCenterStarter.m not included in the iOS build

### ISSUE THREAD

**Issue by supersolid-corentin** [Microsoft/AppCenter-SDK-Unity#241]
Hi,

I ran into an issue when integrating the SDK in my project for iOS. The C# methods in Unity were called when running the build on an iOS device but the native plugin wasn't reacting to them (no native logs were appearing even in verbose mode). If I understand well, the SDK is generating a file called AppCenterStarter.m that is used to launch the SDK. In my case it is generated but that file isn't included in the generated XCode project. After including the file manually, it worked well.

I'm not sure why it does that but I think the issue is linked to the build process in my team. We're developing on Windows and we use Jenkins to launch a build for iOS on a Mac Mini. Each time it is built, the project folder is cleared, the last commit of a specific branch is pulled from a Git repository and the build for iOS is launched on Unity by using CLI.

Maybe it could also be the Unity version. We're using the version 2017.4.12f1. I have seen some defines (UNITY_2018_1_OR_NEWER) in AppCenterPostBuild.cs so I guess that some parts of the build post process may not run correctly.

Sorry I don't have time to investigate more. Thanks in advance for the help!

**Comment by maestersid** [comment]
Hey! I checked in with the team on this one. Do you think you could open a support ticket within the App Center portal (Blue icon on the bottom right) and also potentially share your build scripts? We want to be able to troubleshoot this on our end to confirm the issue.

**Comment by supersolid-corentin** [comment]
Thanks for the quick answer! I will create a ticket and take some time to remove any code not necessary from the build script to reproduce the issue as soon as possible.

**Comment by supersolid-corentin** [comment]
I have tried to reproduce it with just the build script yesterday but I wasn't able to. I guess it may be due to the combination of plugins I've got in my Unity project. I will close the issue as it's not possible for me to share the whole project and it seems to be an edge case that probably won't impact other people.
