### ISSUE TITLE
PC and standalone builds support

### ISSUE THREAD

**Issue by davidezordan** [Microsoft/AppCenter-SDK-Unity#245]
Hi,

I would like to use this SDK in a Unity project targeting PC and standalone builds (now UWP). Are there any plans for this?

Thanks,
Davide

**Comment by maestersid** [comment]
Hi @davidezordan thanks for the feedback. Broader Windows support is on our radar across all our SDK's, including Unity.

**Comment by davidezordan** [comment]
Thank you @jwhiteDev for the confirmation. I am looking forward to trying it with my Oculus Rift project!

**Comment by Strepto** [comment]
https://github.com/microsoft/appcenter/issues/53#issuecomment-518745924

Support is just introduced for .Net Framework in AppCenter, is there any chance of this benefiting the Unity AppCenter variant?

**Comment by AdamBursill-Trimble** [comment]
Any update on Unity Standalone build support?

**Comment by Jamminroot** [comment]
Hey, @AdamBursill-SV, thanks for showing your interest.
I'll address your question to PMs team so that they can have a look.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
