### ISSUE TITLE
AppCenterDemoApp build setting

### ISSUE THREAD

**Issue by junpark12** [Microsoft/AppCenter-SDK-Unity#246]
Hi I followed read me document to test AppCenterDemoApp in unity.
The app has default build setting in unity as windows standalone.
Is this recommended build setting? Or do we have other documentation to change the build setting like UWP 
Thanks

**Comment by maestersid** [comment]
Hi @junpark12 
We don't have any documentation specifically for changing it to UWP, but the steps for adding App Center are the same, and should be supported. Are you running into any specific issues?

**Comment by junpark12** [comment]
Hi @jwhiteDev 
I just started to learn appcenter. So i don't grab the overall process yet like build, deploy..
I want to deploy "AppCenterDemoApp" but i don't know where to deploy.
When i build using default setting, it create "AppCenterDemoApp.exe" in my win 10 PC.
So it looks like this demo app's destination is windows desktop. Is this right?
Thanks.

**Comment by maestersid** [comment]
Yes that is correct, you can run and launch the demo app on your windows machine. You also will want to make sure the app is created in App Center, and associated with the correct app secret so data can be displayed.

**Comment by junpark12** [comment]
Thanks. One more question.
Are there any differences between mobile apps(android, apple) and windows app?
I mean it looks like customers can deploy their mobile app to appcenter devices.
This demo app's case(desktop app), can we deploy this app to any appcenter devices?
Thanks.

**Comment by maestersid** [comment]
Android, iOS and Windows apps are all different. They can be built with tools to make them look and behave similarly, but in the end they are different toolstacks. We support UWP along with the mobile platforms.

The only device limitation you have is we do not have automated testing available for Windows devices. Our device cloud is Android & iOS only.

**Comment by junpark12** [comment]
Thanks a lot for the clarification. Have a good day
