### ISSUE TITLE
iOS 8 crash using lateast AppCenter SDK.

### ISSUE THREAD

**Issue by yuewah** [Microsoft/AppCenter-SDK-Unity#251]
Is it possible to show error message instead of crash on iOS 8 device ?

**Comment by MatkovIvan** [comment]
Hi @yaananth,

As mentioned in [the docs](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/unity#1-prerequisites), the SDK supports only iOS 9.0 or later. Thus, it is assumed that the SDK won't be used on devices with this iOS version.

Thanks,
Ivan
