### ISSUE TITLE
Push: Catch missing Firebase SDK early

### ISSUE THREAD

**Issue by brzGatsu** [Microsoft/AppCenter-SDK-Unity#253]
Please add a verification that the Firebase SDK exists when enabling Push. Right now if Push is enabled and the SDK is missing the App crashes on startup.

**Comment by maestersid** [comment]
This is excellent feedback. Ill circle with the team to look at getting this check in place.

**Comment by maestersid** [comment]
@brzGatsu could you tell us about what caused this? Or SDK should have a dependency on Firebase. Could you share more details on how you saw this issue?

**Comment by brzGatsu** [comment]
I enabled Push without having the Firebase SDK in my project. After sideloading the APK it crashed on startup. The log showed the following: "java.lang.NoClassDefError: Failed resolution of: Lcom/google/firebase/iid/FirebaseInstanceId"

I assume it happened because the SDK was missing - no more crashes after disabling Push. My request is to detect this as soon as push is enabled in the editor.

**Comment by annakocheshkova** [comment]
Hi @brzGatsu, Unity SDk should automatically resolve firebase dependencies at the time of Unity build. 
Do you have firebase aars under `Assets\Plugins\Android`?

**Comment by annakocheshkova** [comment]
@brzGatsu hi, do you have any updates on this? We'd love to answer your questions.

**Comment by annakocheshkova** [comment]
We haven't heard from you in a while, so I'll close this issue. feel free to re-open it if you have any updates.

Thanks!

**Comment by wagenheimer** [comment]
I have the exact same problem. My project crash because of missing Firebase references.

**Comment by guperrot** [comment]
@wagenheimer what about this comment? https://github.com/microsoft/AppCenter-SDK-Unity/issues/253#issuecomment-471481200

**Comment by wagenheimer** [comment]
I updated to AppCenter 2.0.0 and the FireBase References problem is now fixed.

**Comment by guperrot** [comment]
Glad the latest version worked for you and thanks for using AppCenter.
