### ISSUE TITLE
AppSecretDenied  Error

### ISSUE THREAD

**Issue by wagenheimer** [Microsoft/AppCenter-SDK-Unity#261]
Hi!
I'm using Unity 2019.1 and AppCenter 2.0.0.

I'm trying to generate a build with App Center, but it is failing to initialize with this error :

I checked the resulting Android Project, and appcenter-settings.xml is there with the correct appcenter_app_secret.

What Can I try to fix this?

E/AppCenter: Sending logs groupName=group_push id=5067df12-bfb6-4182-b18a-d4bdb394dcf0 failed
    com.microsoft.appcenter.http.HttpException: 401 - CorrelationId: 77276558-1020-43d8-9135-39a8934bc94a  ReasonCode: AppSecretDenied 
        at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doHttpCall(DefaultHttpClientCallTask.java:305)
        at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doInBackground(DefaultHttpClientCallTask.java:319)
        at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doInBackground(DefaultHttpClientCallTask.java:47)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

**Comment by annakocheshkova** [comment]
Hi there @wagenheimer! Can you make sure you enabled verbose logging (**Initial Log Level** setting in **Other setup** section) and send us the full logs?
If it is possible, please also send us a screenshot of your App Center configuration (App Center Behavior).
Thanks!

**Comment by annakocheshkova** [comment]
Hi @wagenheimer just a friendly ping, do you have any updates? We'll be glad to help.

**Comment by wagenheimer** [comment]
![image](https://user-images.githubusercontent.com/315513/57925158-9b1b1800-787d-11e9-9fd7-ba0bd20d267c.png)

Hi Anna... It's still not working, is there any more info you need?

**Comment by annakocheshkova** [comment]
@wagenheimer does this happen only with Push? Analytics, Crashes working fine?

**Comment by wagenheimer** [comment]
Nothing is working!
Strangely enough, Firebase Analytics is working, even disabled on App Center Behavior.

Android Log :

`I/AppCenter: App Center SDK configured successfully.
D/AppCenter: Cannot read instrumentation variables in a non-test environment.
D/AppCenter: Cannot read instrumentation variables in a non-test environment.
D/AppCenter: Cannot read instrumentation variables in a non-test environment.
I/InstantRun: starting instant run server: is main process
D/AppCenter: Using appcenter.0.AES/CBC/PKCS7Padding/256
D/AppCenter: Using appcenter.0.RSA/ECB/PKCS1Padding/2048
I/AppCenterDistribute: Launcher activity restarted.
I/FA: App measurement is starting up, version: 12780
    To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
    To enable faster debug mode event logging run:
      adb shell setprop debug.firebase.analytics.app com.greensaucegames.ForgottenTalesDayoftheDead
D/OpenGLRenderer: Skia GL Pipeline
D/AppCenter: Loaded stored sessions: {1558096313834=1558096313834//1558096313834, 1558096314527=1558096314527/c9946926-c874-4a5d-ae30-5196bb344efc/1558096313834, 1558096442640=1558096442640//1558096442639, 1558096442757=1558096442757/c2336b0d-6288-4168-ad80-01b505d22329/1558096442639}
D/AppCenter: Network 2170 is available.
    Network has been connected.
I/FA: Tag Manager is not found and thus will not be used
I/AppCenter: Changed maximum database size to 10485760 bytes.
D/AppCenter: addGroup(group_core)
D/AppCenter: checkPendingLogs(group_core) pendingLogCount=0
D/AppCenter: App Center initialized.
    removeGroup(group_analytics)
    removeGroup(group_analytics/one)
D/AppCenter: addGroup(group_analytics)
D/AppCenter: checkPendingLogs(group_analytics) pendingLogCount=0
    addGroup(group_analytics/one)
D/AppCenter: checkPendingLogs(group_analytics/one) pendingLogCount=0
I/AppCenter: Analytics service started from application.
D/AppCenter: removeGroup(group_distribute)
D/AppCenter: removeGroup(group_distribute/one)
    addGroup(group_distribute)
D/AppCenter: checkPendingLogs(group_distribute) pendingLogCount=0
    addGroup(group_distribute/one)
D/AppCenter: checkPendingLogs(group_distribute/one) pendingLogCount=0
I/AppCenter: Distribute service started from application.
D/AppCenter: removeGroup(group_push)
    removeGroup(group_push/one)
    addGroup(group_push)
D/AppCenter: checkPendingLogs(group_push) pendingLogCount=0
    addGroup(group_push/one)
D/AppCenter: checkPendingLogs(group_push/one) pendingLogCount=0
D/AppCenterPush: Push token refreshed: c_lRE7K0jow:APA91bHSAdskIL_5fZxltD8ajjbaAbvhh7RHx-TzmABU3lu7-U_ghupRDVlE6_ihkygvg4qKmMBlulHNLuajzq4e59Rpktt1OiMafLYpCIlCAcnI1Yg_rwUjINfPMDSbimeU1XWkYc9y
D/AppCenter: Storing a log to the Persistence database for log type pushInstallation with flags=1
D/AppCenter: Stored a log to the Persistence database for log type pushInstallation with databaseId=7
    enqueue(group_push) pendingLogCount=1
    checkPendingLogs(group_push) pendingLogCount=1
    triggerIngestion(group_push) pendingLogCount=1
D/AppCenter: Trying to get 1 logs from the Persistence database for group_push
D/AppCenter: Returning 1 log(s) with an ID, a26a7337-cc3f-40ff-8d81-1d00dd00517f
    The SID/ID pairs for returning log(s) is/are:
    	null / 7
D/AppCenter: ingestLogs(group_push,a26a7337-cc3f-40ff-8d81-1d00dd00517f) pendingLogCount=0
I/AppCenterPush: Firebase SDK is available, using Firebase SDK registration.
I/AppCenter: Push service started from application.
D/AppCenter: Storing a log to the Persistence database for log type startService with flags=1
D/AppCenter: Stored a log to the Persistence database for log type startService with databaseId=8
D/AppCenter: enqueue(group_core) pendingLogCount=1
    checkPendingLogs(group_core) pendingLogCount=1
D/AppCenterAnalytics: onActivityResumed
D/AppCenter: Storing a log to the Persistence database for log type startSession with flags=1
D/AppCenter: Stored a log to the Persistence database for log type startSession with databaseId=9
    enqueue(group_analytics) pendingLogCount=1
    checkPendingLogs(group_analytics) pendingLogCount=1
W/lesDayoftheDea: Accessing hidden method Ljava/lang/invoke/MethodHandles$Lookup;-><init>(Ljava/lang/Class;I)V (light greylist, reflection)
I/AppCenterDistribute: Not checking in app updates in debug.
D/AppCenter: checkPendingLogs(group_push) pendingLogCount=0
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
I/DpmTcmClient: RegisterTcmMonitor from: com.android.okhttp.TcmIdleTimerMonitor
I/Unity: SystemInfo CPU = ARM64 FP ASIMD AES, Cores = 8, Memory = 5737mb
    SystemInfo ARM big.LITTLE configuration: 4 big (mask: 0xf0), 4 little (mask: 0xf)
I/Unity: ApplicationInfo com.greensaucegames.ForgottenTalesDayoftheDead version 1.23 build f3839357-67db-4fc0-88a8-781c24de53df
    Built from '2019.1/release' branch, Version '2019.1.2f1 (3e18427e571f)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'arm64-v8a', Stripping 'Disabled'
V/AppCenter: Calling https://in.appcenter.ms/logs?api-version=1.0.0...
    Headers: {Install-ID=665c8361-5db1-4a6a-8927-8b375c802766, App-Secret=*****************************************************************41beadd9, Content-Type=application/json}
V/AppCenter: {
      "logs": [
        {
          "type": "pushInstallation",
          "timestamp": "2019-05-17T12:35:25.692Z",
          "device": {
            "sdkName": "appcenter.android",
            "sdkVersion": "2.0.0",
            "model": "Mi A2",
            "oemName": "Xiaomi",
            "osName": "Android",
            "osVersion": "9",
            "osBuild": "PKQ1.180904.001",
            "osApiLevel": 28,
            "locale": "pt_BR",
            "timeZoneOffset": -180,
            "screenSize": "1080x2016",
            "appVersion": "1.23",
            "carrierName": "TIM",
            "carrierCountry": "br",
            "appBuild": "83",
            "appNamespace": "com.greensaucegames.ForgottenTalesDayoftheDead"
          },
          "pushToken": "c_lRE7K0jow:APA91bHSAdskIL_5fZxltD8ajjbaAbvhh7RHx-TzmABU3lu7-U_ghupRDVlE6_ihkygvg4qKmMBlulHNLuajzq4e59Rpktt1OiMafLYpCIlCAcnI1Yg_rwUjINfPMDSbimeU1XWkYc9y"
        }
      ]
    }


V/AppCenter: HTTP response status=401 payload=CorrelationId: e0fcb9b4-67f7-4257-836b-91cd0714c51f  ReasonCode: AppSecretDenied 
V/AudioTrack: obtainBuffer(192) returned 192 = 192 + 0 err 0
E/AppCenter: Sending logs groupName=group_push id=a26a7337-cc3f-40ff-8d81-1d00dd00517f failed
    com.microsoft.appcenter.http.HttpException: 401 - CorrelationId: e0fcb9b4-67f7-4257-836b-91cd0714c51f  ReasonCode: AppSecretDenied 
        at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doHttpCall(DefaultHttpClientCallTask.java:305)
        at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doInBackground(DefaultHttpClientCallTask.java:319)
        at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doInBackground(DefaultHttpClientCallTask.java:47)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
D/AppCenter: Trying to get 100 logs from the Persistence database for group_distribute
D/AppCenter: No logs found in the Persistence database at the moment
D/AppCenter: Deleting all logs from the Persistence database for group_distribute
V/AudioTrack: obtainBuffer(192) returned 192 = 192 + 0 err 0
D/AppCenter: Deleted 0 logs.
    Trying to get 100 logs from the Persistence database for group_push/one
D/AppCenter: No logs found in the Persistence database at the moment
    Deleting all logs from the Persistence database for group_push/one
    Deleted 0 logs.
    Trying to get 100 logs from the Persistence database for group_push
D/AppCenter: No logs found in the Persistence database at the moment
    Deleting all logs from the Persistence database for group_push
D/AppCenter: Deleted 1 logs.
    Trying to get 100 logs from the Persistence database for group_core
V/AudioTrack: obtainBuffer(192) returned 192 = 192 + 0 err 0
D/AppCenter: Returning 1 log(s) with an ID, 97cf2e73-1961-4e42-8362-743e2c91d199
    The SID/ID pairs for returning log(s) is/are:
    	null / 8
    Deleting all logs from the Persistence database for group_core
D/AppCenter: Deleted 1 logs.
    Trying to get 100 logs from the Persistence database for group_analytics
V/AudioTrack: obtainBuffer(192) returned 192 = 192 + 0 err 0
D/AppCenter: Returning 1 log(s) with an ID, d4843eb7-e048-43e4-8c95-1cc968d44820
    The SID/ID pairs for returning log(s) is/are:
    	c197910d-5151-4f90-b531-c58995b09c5c / 9
D/AppCenter: Deleting all logs from the Persistence database for group_analytics
V/AudioTrack: obtainBuffer(192) returned 192 = 192 + 0 err 0
D/AppCenter: Deleted 1 logs.
    Trying to get 100 logs from the Persistence database for group_analytics/one
D/AppCenter: No logs found in the Persistence database at the moment
D/AppCenter: Deleting all logs from the Persistence database for group_analytics/one
D/AppCenter: Deleted 0 logs.
D/AppCenter: Trying to get 100 logs from the Persistence database for group_distribute/one
V/AudioTrack: obtainBuffer(192) returned 192 = 192 + 0 err 0
D/AppCenter: No logs found in the Persistence database at the moment
    Deleting all logs from the Persistence database for group_distribute/one
D/AppCenter: Deleted 0 logs.`

**Comment by annakocheshkova** [comment]
@wagenheimer sorry I didn't notice it before. You app secret seems a little strange (for instance, it has spaces and it clearly shouldn't).
Make sure you copied it from the appliaction overview page, for example:
![image](https://user-images.githubusercontent.com/34677812/57932382-79dd1a80-78c3-11e9-884c-df4fec73fe5c.png)

**Comment by wagenheimer** [comment]
Hi Anna!
I don't believe I make this mistake!
It seems to be working now! Thanks for the support!

**Comment by annakocheshkova** [comment]
Great! Yes, I didn't notice it at first too 🙂 
Closing the issue then.
