### ISSUE TITLE
Is support for AppCenter Auth planned?

### ISSUE THREAD

**Issue by ghost** [Microsoft/AppCenter-SDK-Unity#282]
Is the AppCenter Auth Service on the roadmap for the Unity Plugin?
https://docs.microsoft.com/en-us/appcenter/auth/

If so, is it high priority and coming soon, or low priority?

**Comment by amchew** [comment]
Hey @bjustice-sympatient, thanks for reaching out! App Center Auth support is the next platform that we're actively working on, and it's coming soon. Will continue to keep you updated!

**Comment by maestersid** [comment]
@bjustice-sympatient I would love to learn more about what your team is doing at Sympatient, could you send me an email so we could connect? You can find it in my GitHub profile

**Comment by annakocheshkova** [comment]
Hi @bjustice-sympatient, the Unity 2.4.0 SDK with Auth support has been released, please [check it out](https://github.com/microsoft/appcenter-sdk-unity/releases/tag/2.4.0)!
