### ISSUE TITLE
Make DontDestroyOnLoad optional

### ISSUE THREAD

**Issue by brzGatsu** [Microsoft/AppCenter-SDK-Unity#288]
Hi, can you please make this optional? I run a single scene setup and don't have the App Center Behavior in the scene root which causes a warning.

**Comment by annakocheshkova** [comment]
Hi @brzGatsu! 
This warning is valid - the object should not be destroyed. 
Besides, introducing a public API for a warning will be confusing for other customers.

**Comment by brzGatsu** [comment]
As mentioned, I run a single scene setup so it won't ever be destroyed, hence the request to add a property that allows us to disable the DontDestroyOnLoad call. All other middleware I use provides such a flag. This enables the developers to have full control over the object lifetime, i.e. I instantiate everything including the AppCenterBehaviour on startup from a prefab, our scenes just hold the IoC container configuration (Zenject).

**Comment by annakocheshkova** [comment]
@brzGatsu makes sense. I've created a feature request for this.

**Comment by maestersid** [comment]
Hi @brzGatsu if you have not already done so I would also track our roadmap and other feature requests on our central app center repo here:
Roadmap: https://github.com/microsoft/appcenter/wiki/Roadmap
Feature Requests: https://github.com/microsoft/appcenter/issues

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
