### ISSUE TITLE
Scripting runtime .NET 3.5 is not supported 

### ISSUE THREAD

**Issue by sam-mckay** [Microsoft/AppCenter-SDK-Unity#292]
Currently you cannot use the majority of the crashes API due to a dependency on async/await code which is not supported in C#4 (the only stable version in 2017.4)

To use later versions of C# you have to upgrade to .Net 4.6, this is not recommend as it is unstable/experimental in 2017.4. For large projects the upgrade to 2018.4 is non trivial. 

Synchronous versions (or coroutine implementations) of these methods should be provided in the API.

**Comment by MatkovIvan** [comment]
Hi @sam-mckay,

We **do** support it, and provide coroutine implementations for this methods.
Please refer to the doc https://docs.microsoft.com/en-us/appcenter/sdk/unity-async to learn how to use the async APIs in AppCenter Unity SDK.

Please let us know it something doesn't work for you.

Thanks,
Ivan

**Comment by sam-mckay** [comment]
Hi @MatkovIvan ! 

Ahh perfect, Thank you! That's well hidden in the documentation... A link to that from the getting started guide would've helped a lot here I think :) 

Do you know if the Crashes.GenerateTestCrash Api works for .Net 3.5? I'm trying to migrate from HockeyApp and am yet to see the App Center SDK send crashes through to either App Center or HockeyApp?

**Comment by MatkovIvan** [comment]
> Do you know if the Crashes.GenerateTestCrash Api works for .Net 3.5?

It should.

> either App Center or HockeyApp

Please note that you can only have one crash reporting SDK integrated in your app. See https://docs.microsoft.com/en-us/appcenter/sdk/troubleshooting/ios#crashes-dont-show-up-in-the-portal

**Comment by sam-mckay** [comment]
Great! 

Understood, I've removed the old HockeyApp SDK but was unsure as to where the reports from App Center SDK would go since we've not fully migrated our app in the App Center SDK and as far as I can tell until we do the data should sync between the two? 

Thanks

**Comment by MatkovIvan** [comment]
All your HockeyApp apps are automatically available in App Center. Please read the doc with detailed description of side by side experience: https://docs.microsoft.com/en-us/appcenter/transition/side-by-side

**Comment by sam-mckay** [comment]
@MatkovIvan I understand that part but, what if I'm sending data from the App Center SDK, is that still synced to both platforms? Is it only synced with App Center? Will it only be received once I've moved it as described in the transition center?
![image](https://user-images.githubusercontent.com/9663483/62302796-dedfef80-b472-11e9-87a6-7a023d21437f.png)

**Comment by MatkovIvan** [comment]
* HockeySDK data flows into both, HockeyApp and App Center, even after an app was moved.
* App Center SDK data always only flows into App Center and it's recommended to not upgrade before the app was moved.

**Comment by sam-mckay** [comment]
Thanks! That's really useful to know!

**Comment by MatkovIvan** [comment]
@sam-mckay You are welcome 😃
