### ISSUE TITLE
Crashes SDK support for Unity UWP

### ISSUE THREAD

**Issue by pavlo-shchelkun** [Microsoft/AppCenter-SDK-Unity#297]
At the moment, AppCenter Crashes SDK 2.2.0 does not support Unity UWP platform. It would really help to have this feature.

As an alternative, Microsoft Partner Center provides crash report tracking through Analytics Health section. But it does not help a lot, as it usually registers crashes as 'unknown' due to storage or privacy constrains. In some occasions, it does register crashes with system API calls, but it is not that helpful in comparison to Unity script calls stack-traces.

For exceptions, we can also use Unity Cloud Diagnostics, but it is also restricted and does not support crashes on UWP due to some platform limitation related to crash report interception.

In addition to that, it would be great to have not only crashes supported in the SDK, but also exceptions, errors and even custom logs tracking with AppCenter Diagnostics.

**Comment by maestersid** [comment]
HI @PavloShchelkuniLogos 

Thanks for reaching out. We are working on improving windows support all up right now, having just released [support for WPF and WinForms](https://devblogs.microsoft.com/appcenter/announcing-wpf-and-winforms-support-in-visual-studio-app-center/). Our UWP Native SDK is in preview right now, and once we get that out of preview, we can look to then improve our crash Unity UWP support as well.

**Comment by Staarter** [comment]
Hi guys,
One year later, any news on the AppCenter Crashes support on Unity UWP Platform ?

Thanks

**Comment by AnastasiaKubova** [comment]
Just like any software engineering team, as we focused on building and scaling App Center, we accumulated technical debt that can no longer be sustained and for now, our team is focused on other priorities for the next few months and won’t have the bandwidth to work on this. This means new feature work will be significantly reduced. Switching focus to reliability and performance wasn’t an easy decision, but nevertheless an important one.

You can track the App Center roadmap [here](https://github.com/microsoft/appcenter/wiki/Roadmap).

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
