### ISSUE TITLE
Migrating from HockeyApp to MS App Center with Unity

### ISSUE THREAD

**Issue by shanemccartney** [Microsoft/AppCenter-SDK-Unity#311]
Hi, we are transitioning our apps from HockeyApp o MS App Center. Using the steps here with the Unity SDK :
https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/unity

The issue is that after the app is downloaded we can not get in-app updates to work it always returns this message even though the app is downloaded from https://install.appcenter.ms and is not side-loaded or in a browser in private mode.

Can you provide some assistance and insight in how to resolve this issue as having in-app updates is something we expect for Adhoc releases, this we could do in HockeyApp before the migration.

Here is a screenshot of the message we get in app, as I described above:

![unnamed message](https://user-images.githubusercontent.com/4735713/64303790-0d4e6e80-cfcd-11e9-8d18-18c4499b70a2.png)

**Comment by patniko** [comment]
That should work! Transferring this issue over to our main SDK repo so the team that supports the codebase can assist you with a resolution.

**Comment by annakocheshkova** [comment]
Hi @shanemccartney! Please make sure that your app [is not in the **Development build**](https://docs.microsoft.com/en-us/appcenter/sdk/distribute/unity#enable-in-app-updates-for-debug-builds).
Also, there are a couple of useful notes on that page.

**Comment by shanemccartney** [comment]
Unfortunately the app is not a Unity development build. We have gone through the information on this page. We also tried checking the option Enable Distribute For Debuggable

**Comment by annakocheshkova** [comment]
Then please share the VERBOSE logs from the application @shanemccartney

**Comment by annakocheshkova** [comment]
@shanemccartney we haven't heard from you in a while, do you still have issues? If so, please let us know.
