### ISSUE TITLE
Unity sdk does not send errors or crashes to AppCenter on iOS devices

### ISSUE THREAD

**Issue by cristi2k** [Microsoft/AppCenter-SDK-Unity#316]
Unity sdk does not send errors or crashes to AppCenter on iOS devices.

On Android devices everything works fine.

The App Center Behavior has the correct iOS app secret.
Analytics and Crashes are checked.
iOS build is a debug build.

Set these 2 functions in the Start() function of a monobehaviour.
Microsoft.AppCenter.Unity.Crashes.Crashes.ReportUnhandledExceptions(true);
Microsoft.AppCenter.Unity.Crashes.Crashes.SetEnabledAsync(true);

Checked traffic with Charles and no calls are made to AppCenter.

**Comment by patniko** [comment]
Transferring this to the appropriate repo so you can get support from our dev team there.

**Comment by annakocheshkova** [comment]
Hi there @cristi2k! Please, include a screenshot of your configuration (you can blur out app secrets), Player settings and attach all the VERBOSE logs you get after the start. 
Also check if there are framework files under **Assets** > **AppCenter** > **Plugins** > **iOS** > **<ModuleName>**.
Thanks!

**Comment by cristi2k** [comment]
Hi @annakocheshkova 

I've attached the logs and a screenshot of the configuration.
Can't send you a screenshot of player settings since we don't make the build from Unity, but I can give you some details:
- Scripting Runtime version - .Net 4.x Equivalent
- Scripting Backend - IL2CPP
- Api Compatibility Level - .Net 4.x

**Comment by annakocheshkova** [comment]
Hi there, answered you in Intercom.

**Comment by Tuto96** [comment]
Hi, I seem to be having the same issue with our project, AppCenter works well on Android but not on iOS, we have both analytics and crashes enabled in our project but we are only getting the analytics and not the crashes or errors.

Our configuration details are:

- Scripting Runtime version - .Net 4.x Equivalent
- Scripting Backend - IL2CPP
- Api Compatibility Level - .Net standard 2.0

Thank you

**Comment by annakocheshkova** [comment]
Hi there @Tuto96, could you open a separate issue and fill in the details that are requested in issue template including VERBOSE logs and screenshots? I'm communicating with @cristi2k in Intercom so he has sent those details there.

**Comment by annakocheshkova** [comment]
Besides it might be a different issue since his project setup is complex.

**Comment by annakocheshkova** [comment]
Hi there, it appears the issue was resolved in Intercom. Closing this one.

**Comment by cristi2k** [comment]
Issue is solved, thank for the support.
For anyone encountering the same issue we actually override the "UnityAppController" in one of our scripts that's why the AppCenter was not starting

To solve this, we called "startAppCenter" from our script.

**Comment by SyaoranChang** [comment]
> 
> 
> Issue is solved, thank for the support.
> For anyone encountering the same issue we actually override the "UnityAppController" in one of our scripts that's why the AppCenter was not starting
> 
> To solve this, we called "startAppCenter" from our script.

Hi @cristi2k 

After my project add AppsFlyer Unity SDK,
I encounter this issue, because the sdk also override UnityAppController,
Could you describe more how to solve this about "startAppCenter"?
