### ISSUE TITLE
[ISSUE] Namespace missing or not in the same mold

### ISSUE THREAD

**Issue by liszto** [Microsoft/AppCenter-SDK-Unity#318]
Hello Microsoft devs !
I found one script named "AndroidUtility" with a namespace convention different from any others scripts.
`namespace Assets.AppCenter.Plugins.Android.Utility`
whereas in any other script it's : 
`namespace Microsoft.AppCenter.Unity.Internal.Utility`

so I think the logical thing for Android could be : 
`namespace Microsoft.AppCenter.Android.Utility`

In some others scripts there is no namespace at all like those : 
`AppCenterBehavior`
`AppCenterBehaviorAdvanced`
`AppCenterSettings`
`AppCenterSettingsAdvanced`

Could it be possible to fix this ?

**Comment by annakocheshkova** [comment]
Hi there @liszto! Indeed, namespace in `AndroidUtility` differs from the SDK-related files because this file is just a common utility file and therefore belongs to a different folder and a different namespace. 
The Editor scripts and MonoBehavior are indeed inside no namespace. Is this blocking you somehow?

**Comment by liszto** [comment]
Hi @AnastasiaKubova !
About the Android utility class, there 4 classes that could be defines as Utility stuff :
- AndroidUtility
- JavaDateHelper 
- JavaNumberHelper
- JavaStringMapHelper

And in those 4, the only one that doesn't follow the namespace is the AndroidUtility, that why I asked for this one :) 

Concerning the no namespace classes, it's not an issue for me but it's just to have something uniform.

**Comment by annakocheshkova** [comment]
Oh yeah you're correct @liszto. I will create a bug for that.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to fix this bug in the next year, I'm closing the issue.
