### ISSUE TITLE
[FEATURE] Add asmdef logic in your package.

### ISSUE THREAD

**Issue by liszto** [Microsoft/AppCenter-SDK-Unity#319]
Hello,
could it be possible to add the asmdef logic as Unity package does currently ?
We do this in our project too, and when we add a third party package (like yours) into our project, if  it doesn't contains asmdef it couldn't work.
So we have to create 2 folders basically to keep things clean :
- Editor containing one asmdef file for editor stuff
- Runtime containing one asmdef file for runtime stuff.

FYI : Add this logic to your package won't break non asmdef project ;)

thanks in advance.

**Comment by annakocheshkova** [comment]
Hi @liszto, understood, seems like a reasonable thing, yeah. We will take a look at this and if there are no blockers, implement. Thanks for your suggestion, we really appreciate it! :)

**Comment by liszto** [comment]
Thanks if it's possible to do it cause this is something that create an issue in our projects where hockeyapp was fine before.
Just to give you an example of what plugins looking in our projects.

![image](https://user-images.githubusercontent.com/408031/65489345-39ae2a00-deab-11e9-9cc7-c97e6384fd42.png)

We always disssociate the C# script logic from other native language logic. In this way, it's easier to retrieve scripts instead of searching them in each specific folder at least for us. And in this way, we can keep the asmdef logic simple with only 2 asmdef per project.

For example with your project, we have : 
AppCenter.Runtime with this configuration
![image](https://user-images.githubusercontent.com/408031/65489586-b93bf900-deab-11e9-93e9-1ed1d6512296.png)

AppCenter.Editor with this configuration 
![image](https://user-images.githubusercontent.com/408031/65489540-a0cbde80-deab-11e9-9313-573ff0be354b.png)
In the editor one, there is a reference on Runtime cause it needs references on it to execute or call method from Runtime stuff, like AppCenterBehaviorEditor.cs and AppCenterBehavior.cs.

If you want to be cleaner than this, it could be possible to add more granularity by creating for example : 
AppCenter.Runtime.Android in the Android folder
AppCenter.Runtime.iOS in the iOS folder 
etc....

I could setup this kind of project if you want and propose a PR ;)

**Comment by annakocheshkova** [comment]
@liszto contributions are always welcome! If you have a desire to help and contribute we will really appreciate it. Currently this feature request is in our backlog and I can't say the exact estimate when it's going to be done.

**Comment by liszto** [comment]
Ok thanks for the information.
As I said I can submit a PR if this can help devs to integrate it faster :)

**Comment by Tommigun1980** [comment]
Hi. When will this be implemented?

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
