### ISSUE TITLE
[BUG][ANDROID][OTHERS?] Crashes lib seems to not work on 2.3.0 ?

### ISSUE THREAD

**Issue by liszto** [Microsoft/AppCenter-SDK-Unity#322]
Hello,
I'm trying to make AppCenter plugin's working with our project since yesterday. Today all seems to be configured correctly but the crash library doesn't work.
I supposed it was due to all my modification from your project (as you can see in my 3 previous posts issues @AnastasiaKubova  ;) ).

But then, I tried to download your sample puppet project from this repository with my Android lib download from your 2.3.0 release. And it seems I have the same behaviour than my project.

Each time I tried to access to Crashes projects throw this in my Android Monitor : 

For example with your puppet project when I press "Crashes Enabled" to activate or deactivate the feature I get : 
`09-24 16:10:19.012: E/AppCenter(7860): Crashes needs to be started before it can be used.`

And I get this each time I try to reach any Crashes feature :/ 

The app seems to be initialized correctly with the Use Crashes set to "true".

Any hint  / tip is welcomed ! 

P.S : I never tried others versions from AppCenter I start with this one.

**Comment by liszto** [comment]
In my application, when I try to call myself `Crashes.StartCrashes();`

I get this : 

````
09-24 16:17:20.187: E/Unity(10323): NullReferenceException: Object reference not set to an instance of an object
09-24 16:17:20.187: E/Unity(10323):   at Microsoft.AppCenter.Unity.Internal.AppCenterInternal.ServicesToNativeTypes (System.Type[] services) [0x00016] in D:\Project\MyHemisForFlexom\UnityProject\Assets\Plugins\AppCenter\Scripts\Runtime\AppCenterSDK\Core\Android\AppCenterInternal.cs:153 
09-24 16:17:20.187: E/Unity(10323):   at Microsoft.AppCenter.Unity.Internal.AppCenterInternal.Start (System.Type service) [0x0000c] in D:\Project\MyHemisForFlexom\UnityProject\Assets\Plugins\AppCenter\Scripts\Runtime\AppCenterSDK\Core\Android\AppCenterInternal.cs:129 
09-24 16:17:20.187: E/Unity(10323):   at Microsoft.AppCenter.Unity.Crashes.Internal.CrashesInternal.StartCrashes () [0x00001] in D:\Project\MyHemisForFlexom\UnityProject\Assets\Plugins\AppCenter\Scripts\Runtime\AppCenterSDK\Crashes\Android\CrashesInternal.cs:112 
09-24 16:17:20.187: E/Unity(10323):   at Microsoft.AppCenter.Unity.Crashes.Crashes.StartCrashes () [0x00001] in D:\Project\MyHemisForFlexom\UnityProject\Assets\Plugins\AppCenter\Scripts\Runtime\AppCenterSDK\Crashes\Shared\Crashes.cs:280 
09-24 16:17:20.187: E/Unity(10323):   at (wrapper managed-to-native
```

**Comment by annakocheshkova** [comment]
Hey @liszto! If you use the app from the repo, it's expected. We do not commit native binaries so the app won't build from scratch. In order for it to compile, one needs to import App Center packages from GH release. 
But, I assume you did that on your project, so what did you use: manual integration or Unity Extension? 
And by the way @annakocheshkova (please don't scare @AnastasiaKubova :))

**Comment by liszto** [comment]
Oooops really sorry ! 
I will stop trust my completion :) 

In fact, I use the Unity Extension system into an empty project to retrieve files properly then I integrate them manually into our project. I try to find a better way but because I have to edit hierarchy, scripts, asmdef etc... I prefer to it in that way currently.

So yeah I use the files imported from the Unity Extension (even if I do manual stuff after this)

**Comment by liszto** [comment]
@annakocheshkova I included the native binaries for Android in your puppet repository. So I don't think the issue comes from this (I supposed at least)

**Comment by annakocheshkova** [comment]
Wait, my apologies, I haven't noticed it: why do you call Start() manually? No need to do that in Unity SDK.

**Comment by liszto** [comment]
Yup, I removed it cause it was a stupid mistake from me but the issue still happens.

BUT

I finally found why this issue happens in my project ! 

It seems to be due to the stripping !I investigate more just to be sure of my test, but I got a crash report on AppCenter server few minutes ago so it's probably due to this.

**Comment by annakocheshkova** [comment]
Ok please confirm if that's the case - and then we can rename the title of the issue, I'm sure the solution will be helpful to others facing it.

**Comment by liszto** [comment]
I fact I barely think your base code was ok.

BUT remember my ticket #65 when you use asmdef, Unity redefined an assembly above the code inside the folder at the level of this asmdef or for the files in the folder at the same level.
So when I created my asmdef : AppCenter.Runtime for all your runtime script, in fact I generated an assembly (a true one not something based on the namespace as you could have before). 

So my asmdef files was named : 
![image](https://user-images.githubusercontent.com/408031/65593814-9a179700-df91-11e9-907d-2ac634195843.png)

But in your link.xml you have this currently  : 

```
    
<linker>
    <!-- Need ignoreIfMissing for all of the assemblies because build fails on Mac in some cases without -->
    <assembly fullname="System">
        <!-- Need to use Newtonsoft Json.NET library with IL2CPP build. -->
        <namespace fullname="System.ComponentModel" preserve="all" ignoreIfMissing="1"/>
    </assembly>

    <!-- Keep all our assemblies. -->
    <assembly fullname="Microsoft.AppCenter" preserve="all" ignoreIfMissing="1"/>
    <assembly fullname="Microsoft.AppCenter.Analytics" preserve="all" ignoreIfMissing="1"/>
    <assembly fullname="Microsoft.AppCenter.Crashes" preserve="all" ignoreIfMissing="1"/>
    <assembly fullname="Microsoft.AppCenter.Push" preserve="all" ignoreIfMissing="1"/>
    <assembly fullname="SQLite-net" preserve="all" ignoreIfMissing="1"/>
</linker>
```

When you define an asmdef file as I said it will generate an assembly based on its name so here `AppCenter.Runtime` so in your link.xml I have to write this instead : 

```
<linker>
    <!-- Need ignoreIfMissing for all of the assemblies because build fails on Mac in some cases without -->
    <assembly fullname="System">
        <!-- Need to use Newtonsoft Json.NET library with IL2CPP build. -->
        <namespace fullname="System.ComponentModel" preserve="all" ignoreIfMissing="1"/>
    </assembly>

    <!-- Keep all our assemblies. -->
    <assembly fullname="AppCenter.Runtime" preserve="all"/>
    <assembly fullname="SQLite-net" preserve="all" ignoreIfMissing="1"/>
</linker>
```

And everything is ok after this change, without this change I have this "error entry in Android Monitor" : 
`09-25 14:44:28.395: E/AppCenter(28679): Crashes needs to be started before it can be used.`

**Comment by annakocheshkova** [comment]
Oh! That's interesting. I'll link that to the feature request we've created for asmdef (we wanted to check that NPE as part of it but I didn't realise this is related to your error). 
I guess we can close this one now. Thank you so much for your contributions @liszto :)
