### ISSUE TITLE
[IMPROVEMENTS] Possibility to skip native patching

### ISSUE THREAD

**Issue by liszto** [Microsoft/AppCenter-SDK-Unity#326]
Hello,
on our integration path we found some others dark spot during your native patching.
When people would start themselves your plugin has we do with the `AppCenterBehaviorAdvanced` and your 2 booleans I think it's pointless to try to patch Android native files like the xml patch based on the `AppCenterSettings` and the `AppCenterStarter.m` based on the same file.
Doing this just had some building time whereas it will be not used at all during the start of the app because some devs just doesn't provide the app secret id at this time but just at runtime (as we do).

I think adding one scripting define symbols that could be activated by some devs (like us :D) would be something good.

To keep your behavior and not break any project in use with your system. You could add something like : 
```
#if !DONT_USE_NATIVE_STARTER
//All your editor code for patching each Android & iOS starter/loader file
#endif
```
In this way, only rare devs case as you said yesterday ;) could activate this feature by settings a 
`DONT_USE_NATIVE_STARTER` in there project settings in the Scripting Define Symbols part.

We use this a lot for our build by profiles cause this allow use to build many different case based on the same initial code.

**Comment by annakocheshkova** [comment]
@liszto what you're saying is true except that we can just check the setting at pre-build time and don't do any extra logic with native files patching. 
You are suggesting to use directive instead of 2 checkboxes at all?

**Comment by liszto** [comment]
That was not what I mentionned. 

Cause in our case everything is setup at runtime, the settings files is empty during the build phase. So in fact the appcenter-settings.xml (for Android) and the AppCenterStarter.m (for iOS) will be filled with bad informations. 
The only useful information will be the plugin embbeded in the project cause plugins folders are checked for this.
But from what I can see on Android if the appId is missing (which is our case) the native initialization is ignored. I supposed it would be the same on iOS (not already tested cause our build crash during last build step).

That's why I proposed this scripting defines symbol. In this way you could change almost nothing except this file generation.
I don't have the complete window on the native implication side but from what I can see and with all my testing day yesterday I could supposed it must be ok to only avoid this file generation/patching on build when devs won't have them.

But to what you said here : 

You are suggesting to use directive instead of 2 checkboxes at all?

with the directives set to DONT_USE_NATIVE_STARTER it's (for me at least) logical to autoset to true the 2 checkboxes.

**Comment by annakocheshkova** [comment]
Ok makes sense to me as an additional option for customisation. Thanks for clarifying!

**Comment by annakocheshkova** [comment]
Hey @liszto good news - I've made a little fix today to give users an ability to specify this define symbol. It has a disadvantage though - works well if you attach advanced settings dynamically or after setting up the define symbol, but if they settings are already attached - the **Start from native SDK** checkboxes are not reloaded after adding the define symbol. Force-reloading the script would be too much of a workaround.
