### ISSUE TITLE
[ISSUE] On iOS, your device class generates ambiguous statement with Unity's one

### ISSUE THREAD

**Issue by liszto** [Microsoft/AppCenter-SDK-Unity#328]
Hello,
In our project we have this code : 

```
if (float.TryParse(Device.systemVersion, out versionAsFloat))
```

But with your plugin integrated in this class now there is an ambiguous definition on this one because Unity already have this class definition.

Maybe it could be good to add something to avoid this cause due to this I have to specified at this particular place what we need to use, so in our case I must do : 

```
if (float.TryParse(UnityEngine.iOS.Device.systemVersion, out versionAsFloat))
```

P.S : It could be a side effect from using asmdef. I don't know if you already try to call your class in another with unity's one already there ?
But generally (here at least) we just avoid to declare classes with exact same name than Unity's one (even if sometimes it's painful :/)

**Comment by annakocheshkova** [comment]
Hi there! The reason we have this class is we have identically-named ones in native SDKs. 
With namespaces, it shouldn't be an issue. Is that so with asmdef-s?

**Comment by liszto** [comment]
I just create a non asmdef project from scratch.
So I just use AppCenter Editor Extension to download your package.
Then I create this script : 

```
using UnityEngine;
using UnityEngine.iOS;
using Microsoft.AppCenter.Unity;

public class TestDevice : MonoBehaviour
{
    // Start is called before the first frame update
    void Start()
    {
		Device test = new Device();
    }
}
```

and Visual Studio is not happy with this cause he doesn't know which one to use : 

`Erreur	CS0104	'Device' is an ambiguous reference between 'Microsoft.AppCenter.Unity.Device' and 'UnityEngine.iOS.Device'	Assembly-CSharp	D:\Project\App-asmdef\New Unity Project\Assets\Scenes\TestDevice.cs`

Ambiguous reference is still present so as I supposed it was not due to asmdef but just in cased I prefered to test it ;)

**Comment by annakocheshkova** [comment]
Oh I see. So you use the both `Device` classes in one file and then yeah, it complains. Definitely, we should look for a way to name this better.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
