### ISSUE TITLE
In-app updates disabled

### ISSUE THREAD

**Issue by MrDChristop** [Microsoft/AppCenter-SDK-Unity#333]
### **Description**

I get this error message when i distribute my iOS app. I am trying to enable Distribution updates. AS fas as i understand i just tick the checkbox in AppCenterBehaviour game object.
I receive the email, download the app, then AppCenter asks me to log in, which result in an error message and then to a "In-app updates disabled" message box.
I attach the images which show the workflow.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1.
2.

### **Details**

1. Which SDK version are you using?
2.3.0, Unity 2018.1.1
2. Which platform did you experience the issue on?
    IOS 11
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    iPad Air 3rd gen
4. What third party plugins are you using?
Google AWS
5. Please enable verbose logging for your app using **Initial Log Level** setting and include the logs here:
6. Please share a screenshot of App Center Settings (without app secrets)
7. Please share a screenshot of Build and Player Settings.

![2019-09-30 17 02 53](https://user-images.githubusercontent.com/26302806/65888316-fe7a9200-e3a7-11e9-9924-10acde3bda59.png)

![2019-09-30 17 15 40](https://user-images.githubusercontent.com/26302806/65888338-076b6380-e3a8-11e9-84ec-9aa9c284e69e.png)

![2019-09-30 17 22 43](https://user-images.githubusercontent.com/26302806/65888358-0fc39e80-e3a8-11e9-93d4-0b14c68900f5.png)

![2019-09-30 17 22 51](https://user-images.githubusercontent.com/26302806/65888373-16521600-e3a8-11e9-8d9b-6b1f85a38175.png)

![2019-09-30 17 22 56](https://user-images.githubusercontent.com/26302806/65888400-21a54180-e3a8-11e9-8f5b-4bd11cb2c8d5.png)

**Comment by AnastasiaKubova** [comment]
Hi, @MrDChristop ! Thank you for contacting us! 
Could you please share the verbose [logs](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/unity#adjust-the-log-level) ?

**Comment by MrDChristop** [comment]
Hi Anastasiai was really simple i did not enter the correct IOS app secret number. A digit was offThe error message was really of putting. I stumbled upon this by chance...
ThanksDimi
    On Tuesday, October 1, 2019, 12:58:14 PM GMT+3, AnastasiaKubova <notifications@github.com> wrote:  
 
 
Hi, @MrDChristop ! Thank you for contacting us!
Could you please share the verbose logs ?

**Comment by MrDChristop** [comment]
i was really simple i did not enter the correct IOS app secret number. A digit was off
The error message was really of putting. I stumbled upon this by chance...
