### ISSUE TITLE
AppCenterStarter.m not included in the iOS build

### ISSUE THREAD

**Issue by 0ver1ord** [Microsoft/AppCenter-SDK-Unity#334]
Hi,

I'm trying to reopen the issue #241 , as we're facing the same problem: iOS builds do not send any crash reports.

I've imported the AppCenterCrashes-v2.4.0.unitypackage into our project on Unity v2018.3.6f1, configured as per the guidelines and tested the Android build that worked flawlessly.
Unfortunately iOS didn't go that well and after some testing I've came to the aforementioned issue, just to prove it's our case. We're running builds on the Jenkins server which cleans up the workspace, so the reproduction will be the same, as running the build for the 1st time.

1. Create clean project;
2. Import the plugin;
3. Configure the plugin;
4. Add some test crashing code;
5. Build for iOS;
6. Check that reports are missing.

The build will work the second time, as the AppCenterStarter.m will already be present before the build is initiated.

![image](https://user-images.githubusercontent.com/23434039/65979781-2f28fd00-e476-11e9-8d7f-482fefd78dc4.png)
Build settings won't make much sense, as we have a build script triggering the pipeline.

Here's a screen of the missing file in the generated xcode project:
![image](https://user-images.githubusercontent.com/23434039/65979939-8038f100-e476-11e9-98df-efe8e679b594.png)

**Comment by annakocheshkova** [comment]
Hi there @0ver1ord, could you please elaborate on this phrase:
> The build will work the second time, as the `AppCenterStarter.m` will already be present before the build is initiated.

I don't quite get why is it in your opinion `AppCenterStarter` is built the second time?

P. S. We build our apps on CI as well and we don't face this issue.

**Comment by annakocheshkova** [comment]
Please also share the output from the first build.

**Comment by 0ver1ord** [comment]
Hi @annakocheshkova ,

> I don't quite get why is it in your opinion `AppCenterStarter` is built the second time?

The first time the AppCenterStarter.m file is generated (**created**) by the AppCenterPreBuild -> AppCenterSettingsMakerIos.CommitSettings(), but Unity doesn't include it in the resulting xcode project (not referenced in the project hierarchy, as in the above screenshot, and not copied into the xcode/Libraries/AppCenter/Plugins... folder).

The second time the file already **exists in the folder** and is included in the xcode project by Unity, with whatever changes were made to it during the PreBuild script.

I've implemented a complicated workaround today
[AppCenterPostBuildExtra.txt](https://github.com/microsoft/appcenter-sdk-unity/files/3682315/AppCenterPostBuildExtra.txt)
just to realize while commenting, that it would probably be enough to simply **include this file** in the repo, even just **being empty**.

I don't see the need to share the build output (maybe on Friday with an empty test project), as there's nothing in it, except for the missing AppCenterStarter.m reference.

**Comment by annakocheshkova** [comment]
Ok understood. Thanks for reporting this. We will investigate this.

**Comment by annakocheshkova** [comment]
Hey, sorry for the late response. It was fixed in 2.5.1 version of the SDK. Thanks for the report!
