### ISSUE TITLE
Error on Building for iOS in Unity 2019.3

### ISSUE THREAD

**Issue by wagenheimer** [Microsoft/AppCenter-SDK-Unity#349]
Using Unity 2019.3b8 fails to build project with AppCenter for iOS.

`Exception: Calling TargetGuidByName with name='Unity-iPhone' is deprecated. There are two targets now, call GetUnityMainTargetGuid() - for app or GetUnityFrameworkTargetGuid() - for source/plugins to get Guid instead.
UnityEditor.iOS.Xcode.PBXProject.TargetGuidByName (System.String name) (at /Users/builduser/buildslave/unity/build/External/XcodeAPI/Xcode/PBXProject.cs:168)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <437ba245d8404784b9fbab9b439ac908>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <437ba245d8404784b9fbab9b439ac908>:0)
PBXProjectWrapper.AddBuildProperty (System.String name, System.String value) (at Assets/AppCenter/Editor/PBXProjectWrapper.cs:70)
AppCenterPostBuild.OnPostprocessProject (PBXProjectWrapper project) (at Assets/AppCenter/Editor/AppCenterPostBuild.cs:434)
AppCenterPostBuild.OnPostprocessBuild (UnityEditor.BuildTarget target, System.String pathToBuiltProject) (at Assets/AppCenter/Editor/AppCenterPostBuild.cs:74)
AppCenterPostBuild.OnPostprocessBuild (UnityEditor.Build.Reporting.BuildReport report) (at Assets/AppCenter/Editor/AppCenterPostBuild.cs:42)
UnityEditor.Build.BuildPipelineInterfaces+<>c__DisplayClass17_0.<OnBuildPostProcess>b__1 (UnityEditor.Build.IPostprocessBuildWithReport bpp) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:433)
UnityEditor.Build.BuildPipelineInterfaces.InvokeCallbackInterfacesPair[T1,T2] (System.Collections.Generic.List`1[T] oneInterfaces, System.Action`1[T] invocationOne, System.Collections.Generic.List`1[T] twoInterfaces, System.Action`1[T] invocationTwo, System.Boolean exitOnFailure) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:391)
UnityEditor.BuildPipeline:BuildPlayer(BuildPlayerOptions)
GameConfigEditor:PerformiOSBuild(SerializedObject, String) (at Assets/_Game/Scripts/Game/Editor/GameConfigEditor.cs:725)
GameConfigEditor:OnInspectorGUI() (at Assets/_Game/Scripts/Game/Editor/GameConfigEditor.cs:208)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr) (at /Users/builduser/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:187)
`

**Comment by wagenheimer** [comment]
I fixed the code as the error message recommended, but there are additional errors then.

It seems that release  2.5.0 is imminent to be released. I checked the git and it does not seen to be fixed yet.
 It would possible please fix it in time for the this new Release? 

I cannot make builds while using AppCenter.

**Comment by iamclement** [comment]
Thanks for reporting this issue, we'll look into it.

**Comment by iamclement** [comment]
We will see if we can include the fix in the incoming release.
