### ISSUE TITLE
Android Obsolete Plugin setup

### ISSUE THREAD

**Issue by tamasberesoebb** [Microsoft/AppCenter-SDK-Unity#356]
### **Description**
When I build my app, I'm seeing the following warning:
OBSOLETE - Providing Android resources in Assets/Plugins/Android/res is deprecated, please move your resources to an AAR or an Android Library. See "AAR plug-ins and Android Libraries" section of the Manual for more details.
UnityEditor.EditorApplication:Internal_CallGlobalEventHandler() (at /Users/builduser/buildslave/unity/build/Editor/Mono/EditorApplication.cs:432)

This is caused by this file:
Assets/Plugins/Android/res/value/appcenter-settings.xml 

https://support.unity3d.com/hc/en-us/articles/115005875443-Providing-Android-resources-in-Assets-Plugins-Android-res-is-deprecated

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Add sdk to project
2. Set up sdk properly
3. Build an android build

### **Details**

1. Which SDK version are you using?
    2.4.0
2. Which platform did you experience the issue on?
    - Android 8.0
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Editor
4. What third party plugins are you using?
5. Please enable verbose logging for your app using **Initial Log Level** setting and include the logs here:
6. Please share a screenshot of App Center Settings (without app secrets)
7. Please share a screenshot of Build and Player Settings.

**Comment by guperrot** [comment]
Hi, what exact version of the Unity Editor version are you running? On Mac or Windows?

**Comment by tamasberesoebb** [comment]
> Hi, what exact version of the Unity Editor version are you running? On Mac or Windows?

mac os
2019.2.10f1

**Comment by AnastasiaKubova** [comment]
The fix had been released in [3.1.0](https://github.com/microsoft/appcenter-sdk-unity/releases/tag/3.1.0).
