### ISSUE TITLE
Unity 2019.3.0b9 iOS Xcode Project: Use of undeclared identifier 'MSAppCenter'

### ISSUE THREAD

**Issue by sommerper** [Microsoft/AppCenter-SDK-Unity#367]
### **Description**

When trying to build the Xcode project it fails with:
`Use of undeclared identifier 'MSAppCenter'`
and
`Use of undeclared identifier 'MSAnalytics'`

### **Repro Steps**

1. Create App on AppCenter
2. Import AppCenter SDK and enable Analytics and Crash
3. Create GameObject with AppCenter Behaviour and enter iOS App Secret
4. Build xcode project
5. Get build errors

### **Details**

1. Which SDK version are you using?
    - AppCenterEditorExtensions-v1.2.0.unitypackage
2. Which platform did you experience the issue on?
    - iOS
3. What device version did you see this error on?
   - Mac
4. What third party plugins are you using?
   - None
5. Please enable verbose logging for your app using **Initial Log Level** setting and include the logs here:
```
/Users/username/Development/companyname/gamename/builds/iOS/gamebuild/Libraries/AppCenter/Plugins/iOS/Core/AppCenterStarter.m:10:1: error: use of '@import' when modules are disabled
@import AppCenter;
^
/Users/username/Development/companyname/gamename/builds/iOS/gamebuild/Libraries/AppCenter/Plugins/iOS/Core/AppCenterStarter.m:13:1: error: use of '@import' when modules are disabled
@import AppCenterCrashes;
^
/Users/username/Development/companyname/gamename/builds/iOS/gamebuild/Libraries/AppCenter/Plugins/iOS/Core/AppCenterStarter.m:22:1: error: use of '@import' when modules are disabled
@import AppCenterAnalytics;
^
/Users/username/Development/companyname/gamename/builds/iOS/gamebuild/Libraries/AppCenter/Plugins/iOS/Core/AppCenterStarter.m:68:4: error: use of undeclared identifier 'MSAppCenter'
  [MSAppCenter setLogLevel:(MSLogLevel)kMSLogLevel];
   ^
/Users/username/Development/companyname/gamename/builds/iOS/gamebuild/Libraries/AppCenter/Plugins/iOS/Core/AppCenterStarter.m:77:6: error: use of undeclared identifier 'MSAppCenter'
    [MSAppCenter setMaxStorageSize:maxStorageSize
     ^
/Users/username/Development/companyname/gamename/builds/iOS/gamebuild/Libraries/AppCenter/Plugins/iOS/Core/AppCenterStarter.m:95:22: error: use of undeclared identifier 'MSAnalytics'
  [classes addObject:MSAnalytics.class];
                     ^
/Users/username/Development/companyname/gamename/builds/iOS/gamebuild/Libraries/AppCenter/Plugins/iOS/Core/AppCenterStarter.m:125:6: error: use of undeclared identifier 'MSAppCenter'
    [MSAppCenter setLogUrl:customLogUrl];
     ^
/Users/username/Development/companyname/gamename/builds/iOS/gamebuild/Libraries/AppCenter/Plugins/iOS/Core/AppCenterStarter.m:135:8: error: use of undeclared identifier 'MSAppCenter'
      [MSAppCenter start:customAppSecretValue withServices:classes];
       ^
/Users/username/Development/companyname/gamename/builds/iOS/gamebuild/Libraries/AppCenter/Plugins/iOS/Core/AppCenterStarter.m:138:8: error: use of undeclared identifier 'MSAppCenter'
      [MSAppCenter start:[NSString stringWithFormat:@"target=%@", kMSTargetToken] withServices:classes];
       ^
/Users/username/Development/companyname/gamename/builds/iOS/gamebuild/Libraries/AppCenter/Plugins/iOS/Core/AppCenterStarter.m:141:8: error: use of undeclared identifier 'MSAppCenter'
      [MSAppCenter start:[NSString stringWithFormat:@"appsecret=%@;target=%@", customAppSecretValue, kMSTargetToken] withServices:classes];
       ^
/Users/username/Development/companyname/gamename/builds/iOS/gamebuild/Libraries/AppCenter/Plugins/iOS/Core/AppCenterStarter.m:144:8: error: use of undeclared identifier 'MSAppCenter'
      [MSAppCenter startWithServices:classes];
       ^
11 errors generated.
```
6. Please share a screenshot of App Center Settings (without app secrets)
<img width="593" alt="image" src="https://user-images.githubusercontent.com/1512048/68777830-910e8200-0632-11ea-935d-90d09c34953e.png">

7. Please share a screenshot of Build and Player Settings.
<img width="803" alt="image" src="https://user-images.githubusercontent.com/1512048/68778059-eba7de00-0632-11ea-9108-41a1e538abfa.png">
<img width="679" alt="image" src="https://user-images.githubusercontent.com/1512048/68778090-f498af80-0632-11ea-9ba0-0e2b1901a058.png">

**Comment by Jamminroot** [comment]
Hey, @sommerper, what's the XCode version you are building with?

**Comment by russelarms** [comment]
We haven't heard from you in a while so I'm closing this issue.
Feel free to reopen this issue if it isn't resolved or you have additional questions.

**Comment by ei2kpi-ptc** [comment]
I'm getting these same errors with Unity 2019.3.0b7. I think it has to do with the fact that Unity has changed its build process so it outputs a Framework which is in turn wrapped by a "Host" Native iOS app within Xcode. This makes framework dependencies a little more complex.

I am using XCode 11.1 and here are the errors I am getting... Any ideas on how to set up the dependency correctly?
![image](https://user-images.githubusercontent.com/44373229/69589802-3b838f00-0fbb-11ea-91d6-48c22ad956aa.png)

**Comment by ei2kpi-ptc** [comment]
Hmmm I was able to get past this issue by switching any `@import` to `#include` in `Unity-iPhone > Libraries > AppCenter > Plugins > iOS > Core > AppcenterStarter.m`

So now, it looks like this:
```
//@import AppCenter;
#import <Appcenter/AppCenter.h>

#ifdef APPCENTER_UNITY_USE_CRASHES
//@import AppCenterCrashes;
#import<AppCenterCrashes/AppCenterCrashes.h>
#endif

#ifdef APPCENTER_UNITY_USE_PUSH
@import AppCenterPush;
#import "../Push/PushDelegate.h"
#endif

#ifdef APPCENTER_UNITY_USE_ANALYTICS
//@import AppCenterAnalytics;
#include<AppCenterAnalytics/AppCenterAnalytics.h>
#endif
```

**Comment by ei2kpi-ptc** [comment]
Now, I just get a bunch of Undefined Symbol errors though:
![image](https://user-images.githubusercontent.com/44373229/69590442-81d9ed80-0fbd-11ea-823d-d49bc2310194.png)

**Comment by MatkovIvan** [comment]
Hi @ei2kpi-ptc,

These symbols are from system iOS framework. It resolves automatically if the project uses clang modules (`@import`).
You can add it manually in library file import settings in Unity Editor.

- `SFSafariViewController` - from `SafariServices`
- `WKWebView` - from `WebKit`
- `UNUserNotificationCenter` - from `UserNotifications`

**Comment by sommerper** [comment]
Hey, sorry for the absence. I'm using XCode Version 11.0 (11A420a)

**Comment by ultrakorne** [comment]
@Jamminroot @russelarms Enable Modules in Build Settings is set to No for one of the projects.

changing to yes the settings shown below solves the issue.

![Screenshot 2019-12-04 at 11 32 41](https://user-images.githubusercontent.com/2083769/70135198-dc440f80-1689-11ea-85f7-9d65b995f49e.png)

**Comment by jamilabreu** [comment]
@sommerper Very unorthodox question and method - but what's your asking price for @summer on Twitter? 🙏
