### ISSUE TITLE
Build Errors for Android Unity "D8: Program type already present: com.microsoft.appcenter.analytics.Analytics"

### ISSUE THREAD

**Issue by MugOfPaul** [Microsoft/AppCenter-SDK-Unity#369]
### **Description**

When attempting to build for Android, the build fails. The iOS build for the same project works fine. I get an alert dialog with this massive wall of text:

`com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: /Users/paul/Projects/torch-topo/unity/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/0.jar, /Users/paul/Projects/torch-topo/unity/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/1.jar, /Users/paul/Projects/torch-topo/unity/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/2.jar, /Users/paul/Projects/torch-topo/unity/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/3.jar, /Users/paul/Projects/torch-topo/unity/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/4.jar, /Users/paul/Projects/torch-topo/unity/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/5.jar, /Users/paul/Projects/torch-topo/unity/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/6.jar, /Users/paul/Projects/torch-topo/unity/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/7.jar, /Users/paul/Projects/torch-topo/unity/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/8.jar, /Users/paul/Projects/torch-topo/unity/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/10.jar, /Users/paul/Projects/torch-topo/unity/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/11.jar, /Users/paul/Projects/torch-topo/unity/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/12.jar, /Users/paul/Projects/torch-topo/unity/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/13.jar, /Users/paul/Projects/torch-topo/unity/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/14.jar, /Users/paul/Projects/torch-topo/unity/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/15.jar, /Users/paul/Projects/torch-topo/unity/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/16.jar, /Users/paul/Projects/torch-topo/unity/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/17.jar, /Users/paul/Projects/torch-topo/unity/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/18.jar, /Users/paul/Projects/torch-topo/unity/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/19.jar See the Console for details.`

The console log (edited for brevity, relevant statements in bold):

`Archive:  Assets/AppCenter/Plugins/Android/appcenter-loader-release.aar
  inflating: appcenter-loader-release/AndroidManifest.xml  
  inflating: appcenter-loader-release/R.txt  
  inflating: appcenter-loader-release/classes.jar  
   creating: appcenter-loader-release/libs/
  inflating: appcenter-loader-release/libs/appcenter-push-release.aar  
  inflating: appcenter-loader-release/libs/appcenter-crashes-release.aar  
  inflating: appcenter-loader-release/libs/appcenter-analytics-release.aar  
  inflating: appcenter-loader-release/libs/appcenter-distribute-release.aar  
  inflating: appcenter-loader-release/libs/appcenter-auth-release.aar  
  inflating: appcenter-loader-release/libs/appcenter-release.aar  
   creating: appcenter-loader-release/res/
   creating: appcenter-loader-release/res/values/
  inflating: appcenter-loader-release/res/values/values.xml  
   creating: appcenter-loader-release/values/

  adding: AndroidManifest.xml (deflated 55%)
  adding: R.txt (deflated 82%)
  adding: classes.jar (deflated 8%)
  adding: libs/ (stored 0%)
  adding: libs/appcenter-push-release.aar (deflated 64%)
  adding: libs/appcenter-crashes-release.aar (deflated 64%)
  adding: libs/appcenter-analytics-release.aar (deflated 64%)
  adding: libs/appcenter-distribute-release.aar (deflated 64%)
  adding: libs/appcenter-auth-release.aar (deflated 64%)
  adding: libs/appcenter-release.aar (deflated 64%)
  adding: res/ (stored 0%)
  adding: res/values/ (stored 0%)
  adding: res/values/values.xml (deflated 15%)
  adding: values/ (stored 0%)

Refreshing native plugins compatible for Editor in 1.58 ms, found 0 plugins.
Preloading 0 native plugins for Editor in 0.00 ms.
Android PostProcess task "Checking prerequisites" took 38.1947 ms
Android PostProcess task "Detect Java Development Kit (JDK)" took 6.8848 ms
Android PostProcess task "Detecting Android SDK" took 80.4402 ms
Android PostProcess task "Detect Android NDK" took 0.0041 ms
Android PostProcess task "Trying to find a suitable Android device" took 0.0017 ms

Welcome to Gradle 5.1.1.
BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed
Android PostProcess task "Preparing Managed resources" took 1409.0367 ms
Android PostProcess task "Splitting assets" took 12.1892 ms
Android PostProcess task "Processing OBB assets" took 0.0036 ms
Android PostProcess task "Preparing Unity libraries" took 62.6513 ms
**OBSOLETE - Providing Android resources in Assets/Plugins/Android/res is deprecated, please move your resources to an AAR or an Android Library. See "AAR plug-ins and Android Libraries" section of the Manual for more details.**

Android PostProcess task "Processing resources" took 11.2137 ms
Android PostProcess task "Preparing APK resources" took 7.4156 ms
Android PostProcess task "Processing plugins" took 61.4096 ms
Android PostProcess task "Processing Android libraries" took 6.6288 ms
Android PostProcess task "Checking Graphics API compatibility" took 15.4085 ms
Android PostProcess task "Creating Android manifest" took 94.0535 ms
Unloading 109 Unused Serialized files (Serialized files now loaded: 0)
System memory in use before: 413.0 MB.
System memory in use after: 412.8 MB.

Unloading 151 unused Assets to reduce memory usage. Loaded Objects now: 2376.
Total: 349.365667 ms (FindLiveObjects: 0.550747 ms CreateObjectMapping: 0.130050 ms MarkObjects: 347.374034 ms  DeleteObjects: 1.309617 ms)

Android PostProcess task "Compiling resources" took 440.1081 ms
Android PostProcess task "IL2CPP" took 0.0064 ms
Android PostProcess task "Build native Unity binary" took 0.0012 ms
Android PostProcess task "Zipping symbols" took 0.001 ms
Android PostProcess task "Performance Reporting Symbol Upload" took 0.0013 ms
Android PostProcess task "Preparing streaming assets" took 8.2939 ms
Android PostProcess task "Creating APK expansion package (OBB)" took 0.0068 ms
Android PostProcess task "Exporting project" took 194.5325 ms
**D8: Program type already present: com.microsoft.appcenter.analytics.Analytics$10**

FAILURE: Build failed with an exception.
What went wrong:
Execution failed for task ':transformDexArchiveWithExternalLibsDexMergerForRelease'.
  **Program type already present: com.microsoft.appcenter.analytics.Analytics$10**

 Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.`

### **Details**

1. Which SDK version are you using?
    2.5.1
2. Which platform did you experience the issue on?
    Unity Android
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    n/a
4. What third party plugins are you using?
   Azure Spatial Anchors
5. Please enable verbose logging for your app using **Initial Log Level** setting and include the logs here:

6. Please share a screenshot of App Center Settings (without app secrets)
![image](https://user-images.githubusercontent.com/481248/68903119-f32cbd00-06ee-11ea-93e3-422aff14d309.png)

7. Please share a screenshot of Build and Player Settings.
![image](https://user-images.githubusercontent.com/481248/68903137-fde75200-06ee-11ea-9d03-17d1c58e43dd.png)

**Comment by Jamminroot** [comment]
Hey, @MugOfPaul, thanks for bringing this to our sight. What's your Unity version?

**Comment by Jamminroot** [comment]
Also, is there a chance to have a look at gargle file you get, and know the gradle version you are using? 
Can I also have a look at project structure - to make sure there are no duplicates
And just to make sure - have you tried to remove AC, clean project, and re-implement SDK? Seems like one of aars got stuck somewhere.

**Comment by MugOfPaul** [comment]
Unity 2019.2.11f1

I should mention I had this problem with just Distribute installed as well. When I upgraded to 2.5.1 to try and resolve the issue, I went ahead and turned on Analytics and Crashes. I couldn't find a distinct Gradle log but I'm attaching the full Editor log which shows the Gradle output. 

![image](https://user-images.githubusercontent.com/481248/68961042-3ede7580-0786-11ea-9575-a954b4774fba.png)

![image](https://user-images.githubusercontent.com/481248/68961334-f96e7800-0786-11ea-98d1-03afde05867f.png)

[Editor.log](https://github.com/microsoft/appcenter-sdk-unity/files/3852477/Editor.log)

**Comment by russelarms** [comment]
Hi, it seems to be an error with code duplication, could you try solutions from this [thread](https://issuetracker.unity3d.com/issues/android-duplicate-plugins-with-the-same-names-prevent-from-exporting-a-project-to-android)?

**Comment by MugOfPaul** [comment]
Hi @russelarms as far as I could tell, the solution there was to delete the contents of the Library directory which did not help. 

Given the error is `D8: Program type already present: com.microsoft.appcenter.analytics.Analytics$10` Is there anything wrong with this jar set up? I suppose I could try a full removal of App Center and try again. 

![image](https://user-images.githubusercontent.com/481248/69197379-045a3d00-0ae6-11ea-95fa-c679cda19726.png)

**Comment by MugOfPaul** [comment]
An update: I removed the SDK via the Editor Extension and the Android project builds succesfully. Re-installing 2.5.1 (all packages) and the error comes back. I removed all of the packages except Distribute and the error remained. 

As an aside, the Editor extension is very well done but you are generating quite a few "Coroutiner" objects in the Scene. I would recommend [hiding them from the hierarchy](https://docs.unity3d.com/ScriptReference/HideFlags.HideInHierarchy.html).

**Comment by russelarms** [comment]
@MugOfPaul could you try to build this sample:
https://github.com/olmisa/AndroidBuildSample
Do you have the same problem?

>As an aside, the Editor extension is very well done but you are generating quite a few "Coroutiner" objects in the Scene. I would recommend hiding them from the hierarchy.

Thanks for pointing this out, I'll discuss it with the team.

**Comment by MugOfPaul** [comment]
@russelarms That project built with no issues – using the same instance and version of Unity that is causing issues in my own project.

**Comment by olmisa** [comment]
@MugOfPaul I was able to reproduce the issue. I have found the following interesting thing https://github.com/Azure/azure-spatial-anchors-samples/issues/31 .  'Azure Spatial Anchors' has a dependency on 'AppCenter.Analytics'. That is why the error appears. I have found that 'mainTemplate.gradle' file was added by 'Azure Spatial Anchors' to the 'Assets/Plugins/Android' folder. In this file, I have found the following code

![Screenshot 2019-11-27 at 00 49 22](https://user-images.githubusercontent.com/46326227/69675669-38b69600-10b0-11ea-9d8a-ec8685df28bc.png)

I have added a new excluded group ('com.microsoft.appcenter')

![Screenshot 2019-11-27 at 00 53 09](https://user-images.githubusercontent.com/46326227/69675715-53890a80-10b0-11ea-8f6b-b93b0f1f718c.png)

After that, I was able to build my test project. Maybe it solves your problem.

**Comment by MugOfPaul** [comment]
@olmisa That did the trick! I am now able to build Android with the Distribute SDK installed. 

I would have never figured that out. Thank you so much for your effort. I'm excited to be able to use App Center to share iOS and Android Unity AR apps.
