### ISSUE TITLE
Unity iOS crash is not caught/reported

### ISSUE THREAD

**Issue by mtes133** [Microsoft/AppCenter-SDK-Unity#374]
### **Description**

I have a problem with detecting iOS crashes. 
Logs tell that SDK is configured successfully, Analytics and crashes are enabled. 
Errors are shown in the dashboard if I set Crashes.ReportUnhandledExceptions(true);
But still can't see any crash reported. 
Bitcode is disabled. Symbols are uploaded. Unsymbolicated tab is empty too.
Crash initiated with Crashes.GenerateTestCrash();

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Import AppCenter SDK via AppCenter Editor Extensions into an empty Unity iOS project.
2. Build for iOS and run on a physical device without debugger being attached
3. Generate a test crash

### **Details**

1. Which SDK version are you using?
    - 2.5.1
2. Which platform did you experience the issue on?
    - iOS 12.0.1 & iOS 13.1.2
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - iPhone 8 & iPad Air 3rd gen both physical
4. What third party plugins are you using?
    - none in the test project
5. Please enable verbose logging for your app using **Initial Log Level** setting and include the logs here:
XCode output: [AppCenter verbose logs.txt](https://github.com/microsoft/appcenter-sdk-unity/files/3891250/AppCenter.verbose.logs.txt)
Console output: 
[Logs.txt](https://github.com/microsoft/appcenter-sdk-unity/files/3891264/Logs.txt)

6. Please share a screenshot of App Center Settings (without app secrets)
![Screen Shot 2019-11-26 at 13 03 27](https://user-images.githubusercontent.com/58212584/69620709-d8dbd300-104e-11ea-8304-6d5f5fbae9b9.png)
7. Please share a screenshot of Build and Player Settings.
Scripting Runtime version - .Net 4.x Equivalent
Scripting Backend - IL2CPP
Api Compatibility Level - .NET Standard 2.0

**Comment by ilyashumihin** [comment]
Hi @mtes133, thanks for reaching out.

Based on the log:
> Incorrect usage of notifyWithUserConfirmation: it should only be called from userConfirmationHandler

May be you called the notify function before the callback `Crashes.ShouldAwaitUserConfirmation`?Please check if the API is used as [documented](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/unity#ask-for-the-users-consent-to-send-a-crash-log) or share how exactly do you use this.

**Comment by mtes133** [comment]
@ilyashumihin 
Thanks, but I had the same issue with crashes before I added this call         `Crashes.NotifyUserConfirmation(Crashes.ConfirmationResult.AlwaysSend);` 
I was just desperately adding API calls hoping docs miss something necessary.

**Comment by mtes133** [comment]
By the way `Crashes.ShouldAwaitUserConfirmation` seems to not work on IL2CPP. 
[AppCenter ShouldAwaitUserConfirmation exception.txt](https://github.com/microsoft/appcenter-sdk-unity/files/3895906/AppCenter.ShouldAwaitUserConfirmation.exception.txt)

Here is the log without `Crashes.ShouldAwaitUserConfirmation` which is not required for crashes to work according to the documentation. 
[AppCenter verbose logs after crash.txt](https://github.com/microsoft/appcenter-sdk-unity/files/3895975/AppCenter.verbose.logs.after.crash.txt)

**Comment by MatkovIvan** [comment]
Hi @mtes133,

Based on the logs the crash wasn't detected, so there is no data to send. At this moment, it's not clear why the crash is not detected.

We cannot reproduce this on our end with the repro steps above. Could you please share that test project? Also, please specify which version of Unity Editor you are using.

**Comment by mtes133** [comment]
Hello @MatkovIvan 
Here it is: 
https://drive.google.com/open?id=1jyGruxKLPE-Zo5l_6MLHNDu_j5nScTBV

Unity 2018.4.9f

**Comment by MatkovIvan** [comment]
@mtes133 I don't have access to this file (requested it yesterday)

**Comment by mtes133** [comment]
@MatkovIvan Sorry, seems like there is a corporate restriction, therefore there is no way to share it publicly and I received no request. 
Try this link please: https://drive.google.com/open?id=1zJ_493GgbmvrKLZEzkJ7OiA6Qb5qH8mP

**Comment by ilyashumihin** [comment]
@mtes133, please try to follow next steps:
1. Open build settings
2. Open player settings
3. Select player tab (on left panel)
4. Pick IOS settings
5. Go to 'Debugging and crash reporting'
6. Disable flag in 'Enable CrashReport API'

Also set the flag 'Development Build' in the Build Settings to enable state (see [note](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/unity#generate-a-test-crash)).

**Comment by mtes133** [comment]
Thank you. That helped. Would be great if it was in the documentation.
