### ISSUE TITLE
Coroutiner not destroyed due to 403 responses to GET requests editor extensions make

### ISSUE THREAD

**Issue by mtes133** [Microsoft/AppCenter-SDK-Unity#381]
### **Description**

For the last week I am getting exceptions inside the editor due to the editor extensions. 
There is a GET request to https://api.github.com/repos/Microsoft/AppCenter-SDK-Unity-Extension/git/refs/tags which returns HTTP/1.1 403 Forbidden 
So the Coroutiner is not destroyed and there are always those errors when you run the game inside the editor: 
```
Some objects were not cleaned up when closing the scene. (Did you spawn new GameObjects from OnDestroy?)
The following scene GameObjects were found:
Coroutiner

[App Center EdEx MSG334] App Center Editor Extensions: HTTP/1.1 403 Forbidden
```

Maybe there should be a flag in the AppCenter window that turns off all those unnecessary requests?

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Import AppCenter Editor Extensions into an empty Unity project.
2. Run inside the editor

### **Details**

1. Which SDK version are you using?
    - 2.5.1
2. Which platform did you experience the issue on?
    - Unity Editor OSX
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - 
4. What third party plugins are you using?
    - none in the test project
5. Please enable verbose logging for your app using **Initial Log Level** setting and include the logs here:

6. Please share a screenshot of App Center Settings (without app secrets)
![Screen Shot 2019-11-26 at 13 03 27](https://user-images.githubusercontent.com/58212584/69620709-d8dbd300-104e-11ea-8304-6d5f5fbae9b9.png)
7. Please share a screenshot of Build and Player Settings.
Scripting Runtime version - .Net 4.x Equivalent
Scripting Backend - IL2CPP
Api Compatibility Level - .NET Standard 2.0

**Comment by annakocheshkova** [comment]
Hi there, these requests are not unnecessary, and they not always return 403. This might happen though if there are too many of requests and daily limit is reached. Are you actively using extension or mostly not? If second is true, we might need to revisit our extension logic.

**Comment by mtes133** [comment]
Hello.
Well I see that 403 is not returned to every request. But still every time I am getting:
`Some objects were not cleaned up when closing the scene. (Did you spawn new GameObjects from OnDestroy?)
The following scene GameObjects were found:
Coroutiner
`
Which wasn't present the last week, as well as no 403 had been seen before.

> Are you actively using extension or mostly not?

It makes decent amount of calls on editor start. And every time play mode is started. So it sums up to a lot of calls.

**Comment by annakocheshkova** [comment]
Ok I see. I created a ticket to reduce the amount of GH API calls. We are going to keep track of this in the issue I created in the extension repository (see the linked issue above). I'm closing this one. 

Thanks!

**Comment by Jamminroot** [comment]
Hey, @mtes133, there's update on this ticket (refer to the new page from now on):
https://github.com/microsoft/AppCenter-SDK-Unity-Extension/issues/37/#issuecomment-566124820
