### ISSUE TITLE
The function appcenter_unity_ns_string_to_cstr copies an NSString to char* incorrectly

### ISSUE THREAD

**Issue by RickyRoeslerMS** [Microsoft/AppCenter-SDK-Unity#404]
### **Description**

The function `appcenter_unity_ns_string_to_cstr` in NSStringHelper will, in some circumstances, incorrectly copy an `NSString` to a `char*` array. The function uses `[nsstring length] + 1` to calculate the length of the `char*` array to allocate. It then converts the `NSString` from UTF-16 to UTF-8 and copies it into the newly created array. 

The problem is that `[nsstring length]` is NOT the same as the length of the string after converting to UTF-8. Certain characters require a longer representation in UTF-8 than they do in UTF-16. This means that the allocated array can be shorter than the space required to store the full UTF-8 string.

Furthermore, the string copy is done using the function `strncpy` which does not guarantee that the copied string is null-terminated. If the specified length is less than the source string, the destination string will not be null terminated. This may lead to code reading past the end of the returned string.

The function should either use NSString's `lengthOfBytes` or perform a `strlen` on the UTF-8 string.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Pass the following string into the function: @"what a fast 🐌!"
2. Notice that the returned C# has dropped the exclamation mark

### **Details**

1. Which SDK version are you using?
    2.5.3
2. Which platform did you experience the issue on?
    iOS
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    N/A
4. What third party plugins are you using? 
    N/A
5. Please enable verbose logging for your app using **Initial Log Level** setting and include the logs here:
    N/A    
6. Please share a screenshot of App Center Settings (without app secrets)
    N/A
7. Please share a screenshot of Build and Player Settings.
    N/A

**Comment by AnastasiaKubova** [comment]
The fix had been released in [3.1.0](https://github.com/microsoft/appcenter-sdk-unity/releases/tag/3.1.0).
