### ISSUE TITLE
AppCenterAuthPackage 404 when installing SDKs

### ISSUE THREAD

**Issue by sleroux** [Microsoft/AppCenter-SDK-Unity#443]
### **Description**

When doing a fresh install of the AppCenter SDK 3.1.0, the editor pane throws an HTTP 404 error when downloading the associated packages. Digging into it, it seems that the AppCenterAuthPackage is still trying to be pulled down but doesn't have a published release for 3.1.0

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Install AppCenter-SDK-Unity package
2. Click on Install SDKs in editor pane

### **Details**

1. Which SDK version are you using?
    - 3.1.0
2. Which platform did you experience the issue on?
    - MacOS

**Comment by olmisa** [comment]
Hello, @sleroux , as I understand you try to install SDK through SDK Unity Extension 1.2.0. This issue should be fixed here https://github.com/microsoft/AppCenter-SDK-Unity-Extension/pull/39 . So, the new Unity SDK Extension version will be released soon and all should work fine with a new version.
Thanks.

**Comment by sleroux** [comment]
Yup that's correct. Thanks for the update!

**Comment by olmisa** [comment]
Hello, @sleroux 
SDK Unity Extension 2.0.0 released and all should work as expected without any 404 errors.
Thanks
