### ISSUE TITLE
Hololens 2 Automatic Update checker

### ISSUE THREAD

**Issue by mirzasohailbaig** [Microsoft/AppCenter-SDK-Unity#452]
### **Description**

I installed my UWP app on Hololens 2 by sideloading through device portal. However when I create a distribute release through appcenter I don't get an update prompt on Hololens 2 nor does it auto download the update, even though I have (use Distribute checked, Update track set to Public, Automatic Check for Update checked, and my build is not a devolopment build).  I initially thought this might because the app wasn't installed through appcenter so that's why its not updating. However I don't see an appcenter app on Microsoft store similar to how there is one for android "Visual Studio App Center"  so how do I go about installing the app and its updates for HL2 ? I even tried to do it via the web browser app on hololens but that only downloads the .msix file, which the hololens doesn't know what to do with it. Please note the hololens is listed on app center for analytics.

### **Details**

1. Which SDK version are you using?
    - 3.2.0
2. Which platform did you experience the issue on?
    - UWP 
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Hololens 2, physical device
4. What third party plugins are you using?
 none that would conflict with appcenter.
![issue](https://user-images.githubusercontent.com/8581543/81456092-d382c880-9156-11ea-89b3-f0ec4a1bfc18.jpg)

**Comment by russelarms** [comment]
Hi there, thanks for reaching out, we'll look into this.

**Comment by russelarms** [comment]
Hi @mirzasohailbaig!
Unfortunately, we [don't officially support](https://docs.microsoft.com/en-us/appcenter/general/platform-service-matrix) Hololens on Unity UWP.
You may be able to make it work, but we haven't verified it and can't guarantee it works.

~~You may share [verbose logs](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/unity#adjust-the-log-level) from your device filtered by AppCenter word and we will see if we can help or advise something.~~

**Comment by guperrot** [comment]
In-app updates are not implemented on Windows applications. Unity UWP is only implemented for Analytics and Push.

The matrix mentioned in the previous comment shows Distribute but the support is for the server side part to upload and download application builds on App Center. The SDK itself does not have the in-app updates features for Windows as shown in https://docs.microsoft.com/en-us/appcenter/sdk/.

**Comment by mirzasohailbaig** [comment]
Thanks for the prompt replies any chance this will be added in the future ? Plus diagnostic on unity UWP?

**Comment by russelarms** [comment]
@mirzasohailbaig I'll address your question to our PM.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.

**Comment by SBaig-Figo** [comment]
Thank you, I appreciate you getting back to me.
