### ISSUE TITLE
Migrate to Unity package manager

### ISSUE THREAD

**Issue by thegoldenmule** [Microsoft/AppCenter-SDK-Unity#458]
**Describe the problem**

It is currently difficult to integrate App Center and to manage App Center integrations across multiple projects. To share systems between games, it is becoming common to create Unity UPM (Unity Package Manager) packages that can specify their own external dependencies. These are not the same as `.unitypackage` files. Then it's a simple matter of adding the new package to each game's manifest. Integrating App Center in 10 of our games requires a lot of overhead.

Further, say we'd like all of our games to use App Center and to use a similar setup (we want to integrate it with our own logger, we want app updates to function in a certain way, we want X, Y, and Z metadata added to all crash reports)-- there is currently not an easy way to do this. We can't keep that App Center integration code in its own package with each game pulls in, because the SDK doesn't like being in a package, and we can't define it as a dependency to begin with.

**Describe the solution you'd like**

Ideally, the App Center SDK would be broken in to Unity packages. I don't know the history of the project, but it seems the Editor Extension Plugin predates Unity plugins and was an attempt to basically provide the same functionality. Now that Unity natively supports package management, it'd be great if the SDK were migrated away from the Editor Extension Plugin and onto Unity packages.

**Describe alternatives you've considered**

We have tried wrapping the SDK in our own packages, but it is very high touch. We have to move a lot of files around and make changes to custom inspectors and hardcoded paths. This approach makes updates very difficult as each SDK release would require us to go back and make all our changes again, or try to hand merge into our fork.

**Comment by aphexyuri** [comment]
@thegoldenmule totally second this, Package Manager implementation is imperative. Do you perhaps have folk or repo with the changes that we can collaborate on?

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us.
You can integrate  App Center via packages, please see [this](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/unity#31b-install-individual-packages) guideline.

**Comment by thegoldenmule** [comment]
@AnastasiaKubova Unity has overloaded the word "package" at this point, but the `.unitypackage` file that guideline suggests using is not the same as UPM (Unity Package Manager) packages. See the [Unity documentation](https://docs.unity3d.com/Manual/CustomPackages.html) for more information on the differences.

**Comment by thegoldenmule** [comment]
@aphexyuri No, we haven't started a fork or branch of this as it's a fairly large organizational change to the repo.

**Comment by shaunburns** [comment]
Has their been any movement on this?
Supporting UPM format would be really great

**Comment by AnatolyPristensky** [comment]
Hello @shaunburns,
Currently it doesn't simplify our dependency management and doesn't fit to our priority order, so we don't have ETA of this feature at this moment.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
