### ISSUE TITLE
FormatException: String was not recognized as a valid DateTime.

### ISSUE THREAD

**Issue by olgv** [Microsoft/AppCenter-SDK-Unity#462]
### **Description**

Here is the complete Unity log error:
```
FormatException: String was not recognized as a valid DateTime.
System.DateTimeParse.Parse (System.String s, System.Globalization.DateTimeFormatInfo dtfi, System.Globalization.DateTimeStyles styles) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.DateTime.Parse (System.String s) (at <437ba245d8404784b9fbab9b439ac908>:0)
AppCenterEditor.AppCenterEditorPrefsSO.get_EdSet_lastEdExVersionCheck () (at Assets/AppCenterEditorExtensions/Editor/Scripts/Utils/AppCenterEditorPrefsSO.cs:67)
AppCenterEditor.AppCenterEditor.GetLatestEdExVersion () (at Assets/AppCenterEditorExtensions/Editor/AppCenterEditor.cs:297)
AppCenterEditor.AppCenterEditor.OnEnable () (at Assets/AppCenterEditorExtensions/Editor/AppCenterEditor.cs:48)
```
A minor one but annoying and easy to fix.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Make a new Unity project
2. Add the `App Center Behaviour`object

### **Details**

1. Which SDK version are you using?
    - App Center Editor Extensions 2.0.0
    - SDK 3.2.0
2. Which platform did you experience the issue on?
    - Unity 2019.4.x Editor
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - not applicable
4. What third party plugins are you using?
    - AVProVideo
    - DOTween
    - EnhancedScroller v2
    - TextMesh Pro
5. Please enable verbose logging for your app using **Initial Log Level** setting and include the logs here:
6. Please share a screenshot of App Center Settings (without app secrets)
7. Please share a screenshot of Build and Player Settings.

**Comment by olmisa** [comment]
Hello @olgv 
this issue should be already fixed here https://github.com/microsoft/AppCenter-SDK-Unity-Extension/pull/45 . The next SDK extension release should contain this fix.
Thanks

**Comment by olgv** [comment]
Sounds great! 
Thanks @olmisa
