### ISSUE TITLE
AppCenter Unity for Android build updates appcenter-loader-release.aar on every APK re-build

### ISSUE THREAD

**Issue by jgalmeidah** [Microsoft/AppCenter-SDK-Unity#473]
### **Description**

AppCenter Unity for Android build updates appcenter-loader-release.aar on every APK re-build, causing git to flag as changed.   This is often missed by devs and checked in.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Delete existing APK
2. Build and Run for Android
3. Notice it git version control that appcenter-loader-release.aar is updated, with no changes.

Note that if step1 is skipped the issue does not reproduce.

### **Details**

1. Which SDK version are you using?
    - 3.3.1
2. Which platform did you experience the issue on?
    - Unity 2018.4.16f1
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Windows10
4. What third party plugins are you using?
5. Please enable verbose logging for your app using **Initial Log Level** setting and include the logs here:
6. Please share a screenshot of App Center Settings (without app secrets)
7. Please share a screenshot of Build and Player Settings.

I noticed that in AppCenterPreBuild.cs, in the function  AddSettingsFileToLoader (under the UNITY_ANDRIOD preprocessor), the aar file is (1) required, (2) decompressed and then (3) recompressed with no apparent changes.

Is this needed?

**Comment by olmisa** [comment]
Hi @jgalmeidah ,
to solve this problem https://github.com/microsoft/appcenter-sdk-unity/issues/356 we added logic which patch _**appcenter-loader-release.aar**_ and add _**appcenter-settings.xml**_ as resource. 
Maybe it is applicable to add _*.aar_ files to _gitignore_ in your project?
Thanks

**Comment by jgalmeidah** [comment]
The way I understand how git and gitignore works, adding the file to the .gitignore will not solve the issue (because this is a tracked file that is changing).
I added all kinds of rules to .gitignore anyway, but git still flags the file as changed.
The only way I found is to use git update-index --skip-worktree.  Unfortunately each dev has to do this, which is a pain.

See https://docs.microsoft.com/en-us/azure/devops/repos/git/ignore-files?view=azure-devops&tabs=visual-studio

At any rate, I still do not understand how decompressing and recompressing without changes fixes the original #356 bug.

**Comment by olmisa** [comment]
@jgalmeidah have you tried this https://docs.microsoft.com/en-us/azure/devops/repos/git/ignore-files?view=azure-devops&tabs=visual-studio#permanently-stop-tracking-a-file ?
To fix the bug we added the logic which appends a file with actual settings to _**appcenter-loader-release.aar**_ . It is not just unzip and zip again.
Thanks

**Comment by AnastasiaKubova** [comment]
We haven’t heard from you in a while so I’m closing this issue.
Feel free to reopen this issue if it isn’t resolved or you have additional questions.

**Comment by Decavoid** [comment]
This issue is still active in AppCenter Unity v.4.4.0.
As already mentioned, in `Assets\AppCenter\Editor\AppCenterPreBuild.cs`, method `AddSettingsFileToLoader` unconditionally unzips and zips the file `appcenter-loader-release.aar` on each build.

**Comment by aleksandr-dorofeev** [comment]
Hello @Andreyul 
Have you tried this [way](https://docs.microsoft.com/en-us/azure/devops/repos/git/ignore-files?view=azure-devops&tabs=visual-studio#permanently-stop-tracking-a-file)?

**Comment by Decavoid** [comment]
@aleksandr-dorofeev I tried adding this file to .gitignore. This results in an exception being raised when building the player.
```
IOException: Failed to load dependency file appcenter-loader-release.aar
AppCenterPreBuild.AddSettingsFileToLoader (AppCenterSettingsMakerAndroid settingsMaker) (at Assets/AppCenter/Editor/AppCenterPreBuild.cs:108)
AppCenterPreBuild.OnPreprocessBuild (UnityEditor.BuildTarget target, System.String path) (at Assets/AppCenter/Editor/AppCenterPreBuild.cs:33)
AppCenterPreBuild.OnPreprocessBuild (UnityEditor.Build.Reporting.BuildReport report) (at Assets/AppCenter/Editor/AppCenterPreBuild.cs:22)
UnityEditor.Build.BuildPipelineInterfaces+<>c__DisplayClass15_0.<OnBuildPreProcess>b__1 (UnityEditor.Build.IPreprocessBuildWithReport bpp) (at <ad50112e30b445fdbf80d5814c3cbcf6>:0)
UnityEditor.Build.BuildPipelineInterfaces.InvokeCallbackInterfacesPair[T1,T2] (System.Collections.Generic.List`1[T] oneInterfaces, System.Action`1[T] invocationOne, System.Collections.Generic.List`1[T] twoInterfaces, System.Action`1[T] invocationTwo, System.Boolean exitOnFailure) (at <ad50112e30b445fdbf80d5814c3cbcf6>:0)
UnityEditor.BuildPipeline:BuildPlayer(BuildPlayerOptions)
AutomationManager:BuildPlayer(BuildTargetGroup, BuildType, String, BuildTarget, BuildOptions) (at Assets/Scripts/Editor/Build/AutomationManager.cs:580)
```

**Comment by DmitriyKirakosyan** [comment]
Hi @Andreyul , you would need this file in repo, but you can stop tracking updates on this file using [`git update-index --skip-worktree <file path>`](https://learn.microsoft.com/en-us/azure/devops/repos/git/ignore-files?view=azure-devops&tabs=visual-studio-2022#use-git-update-index-to-ignore-changes).

Back to the initial issue, I agree that in most cases the unzip/zip procedure is not necessary. We should avoid updating the file if there were not changes in the app center settings.
Let's keep it open as a bug.

**Comment by Decavoid** [comment]
skip-worktree is not a good solution because every developer in our team would have to apply this. After a fresh git clone checkout this setting is lost.

**Comment by travis-tap-3d** [comment]
Is there any estimate to a fix for this bug? The workaround really isn't a good long term fix for reasons everyone else has already mentioned.

**Comment by DmitriyKirakosyan** [comment]
We are tracking the item on our board, but no ETA for it. Contribution is always welcome :)

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to fix this bug in the next year, I'm closing the issue.
