### ISSUE TITLE
Cannot Build App with Unity's OpenJDK?

### ISSUE THREAD

**Issue by iiidefektiii** [Microsoft/AppCenter-SDK-Unity#478]
### **Description**

Building with Symbols and the Unity installed OpenJDK I cannot build with an error stating OpenJDK does not contain the required Java to process Android Libraries. Does it require the Oracle JDK?

### **Repro Steps**

1. Install Unity with OpenJDK. 
2. Do Initial SDK Setup.
3. Build App

### **Details**

1. Which SDK version are you using?
    3.3.1
2. Which platform did you experience the issue on?
    Android 7+
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    Editor
4. What third party plugins are you using?
    None. Only Unitys built in (Addressables, Device Simulator, 2D Sprite)
5. Please enable verbose logging for your app using **Initial Log Level** setting and include the logs here:
    Does not build. Hangs
6. Please share a screenshot of App Center Settings (without app secrets)
    No an App Center Issues as it won't build in Unity
7. Please share a screenshot of Build and Player Settings.
![BuildSettings](https://user-images.githubusercontent.com/26176146/98968472-b6e79480-24db-11eb-9561-b7e8f9bc70c4.PNG)

![Capture](https://user-images.githubusercontent.com/26176146/98964954-6ec67300-24d7-11eb-84b2-316b421580d1.PNG)

**Comment by iiidefektiii** [comment]
Do not know what I did to resolve but seems to have resolved.

**Comment by iiidefektiii** [comment]
Closed the app and opened it again and now I get the error message again. Which is affecting my build.

**Comment by Jamminroot** [comment]
Hey! Thanks for bringing this to our sight.

Can you share Unity build logs? That would help us troubleshoot the problem.

Also, does it reproduce on new empty project with only App Center implemented?

The version is 2020.1.4f1 as I see on the screenshot, right?

**Comment by iiidefektiii** [comment]
2020.1.12f1 is the version. I will get you the logs when I am at my pc and try in it in an empty project. One thing I did do is remove all app center sdk's and folders from my project and the error went away. When it is in the project every time I even hit play it shows up.

**Comment by Jamminroot** [comment]
Okay, waiting for logs.

Meanwhile - I've tested build with clean project but, well, nothing did reproduce, so having logs or a sample (empty) project where the problem is reproduced - would really help me out.

**Comment by iiidefektiii** [comment]
@Jamminroot 

Is this the log you are looking for? Also a few things I have found. 

- Blank zip project with just App center is to big to upload here. But i literally just created a new 2020.1.12f1 project. Imported the SDK and switched to Android Platform.
- Blank project with just app center. Once i swtich to Android I get the same error message above in first post, 
- Also in resolvers. If I do not have iOS module added to Unity I receive an error that it doesnt know which platform to use. No Biggie.
- I have an older project that is using 3.3.0. I do not get this popup error at all with the same version of unity. (2020.1.12f1)

[EditorLog.txt](https://github.com/microsoft/appcenter-sdk-unity/files/5537914/EditorLog.txt)

I also do not see any of this error in the logs. Only in Unity but considering that it works fine in 3.3.0 could it be something with the 3.3.1 SDK and OpeNJDK?
![Android Unity Reommended](https://user-images.githubusercontent.com/26176146/99092897-cb8d6080-259f-11eb-9ef4-a9244908a831.PNG)

**Comment by vvechkanov** [comment]
Hey!
Could you please reinstall JDK and share the result? Fo this just remove the directory mentioned in the popup and then in UnityHub install JDK again. I was reproducing this on my laptop with the same Unity and SDK versions and this is working correctly for me.

**Comment by iiidefektiii** [comment]
@vvechkanov Just curious. When I install Unity ( i know this isn't with this SDK) I ahve to turn my firewall and windows defender off in order for OpenJDK and everything else to install. Is this the case for you as well? Kind of wondering while I try what you just mentioned.

Also wondering what you meant by you were reproducing but then said its working correlty. Were you having the same error and then reinstalled and it worked correctly?

**Comment by vvechkanov** [comment]
Hi!
Sorry, I think I used the wrong words. I meant I was trying to reproduce your issue, but with no success. Everything is working correctly. 
Also one more question. You are installing App Center using [Extension Editor](https://github.com/Microsoft/AppCenter-SDK-Unity-Extension)?

**Comment by russelarms** [comment]
Hi @iiidefektiii!
We haven't heard from you in a while, so I'm closing this issue. Please reopen/comment if you have more details or have any other questions.
