### ISSUE TITLE
Can't build iOS build 

### ISSUE THREAD

**Issue by IgorGalimski** [Microsoft/AppCenter-SDK-Unity#489]
Hi!
I've faced an issue with build iOS on 4.1.0 version
<img width="1543" alt="Screen Shot 2021-03-31 at 12 45 14" src="https://user-images.githubusercontent.com/19680568/113133485-62457b80-9228-11eb-9724-7bb267c03480.png">

To fix - need to rename MSException to MSACException
<img width="905" alt="Screen Shot 2021-03-31 at 13 54 00" src="https://user-images.githubusercontent.com/19680568/113133706-a173cc80-9228-11eb-8332-3a66076b61c9.png">

**Comment by AnastasiaKubova** [comment]
Hi, @IgorGalimski ! Thanks for getting in touch with us! 
I am trying to reproduce it locally, but for me all work well. Could you please clarify did you update App Center SDK and what the previous version you used? Does it happen on an empty project?

**Comment by IgorGalimski** [comment]
Hi, @AnastasiaKubova!
In a sample project it works well for me, but in my work project - doesn't work
Before we used 3.2.1

**Comment by AnastasiaKubova** [comment]
@IgorGalimski, Looks like this is a cache issue. Could you please try to clean the cache (for example via `git clean -dfx` command) or try to reinstall the App Center SDK dependencies and let me know about the result?

**Comment by IgorGalimski** [comment]
@AnastasiaKubova 
I've tried with cloning new repo on two Jenkins machines, and locally -it failed everywhere
I've also tried to reinstall sdk

**Comment by AnastasiaKubova** [comment]
@IgorGalimski, could you please clarify how you install App Center SDK, via App Center Unity Editor Extensions or manually?

**Comment by IgorGalimski** [comment]
@AnastasiaKubova 
Both variants

**Comment by AnastasiaKubova** [comment]
Thanks for the additional information. I need some time to double check it.

**Comment by AnastasiaKubova** [comment]
Hi, @IgorGalimski ! I checked this behavior and was able to reproduce your issue. There are reproduce steps and a workaround to avoid this build issue after updating App Center SDK:

- Create Unity project and manually install version 3.2.1 of App Center SDK packages;
- Build and run the iOS app;
- Close app, remove previous iOS build, remove App Center SDK folder from Assets folder;
- Install new App Center SDK packages with the latest version and check that the new App Center SDK folder was created in the Assets folder again;
- Build and run the iOS app again - build successfully.

Could you please try to repeat these steps and let me know about the results?

**Comment by IgorGalimski** [comment]
Hi, @AnastasiaKubova!
Yes, it works well in a sample project. But it doesn't build in my work project

**Comment by AnastasiaKubova** [comment]
@IgorGalimski I checked this behavior on the existing project and can confirm that I was able to reproduce this issue and the steps above resolve this issue. 
I am sure that it related to the cache issue, not SDK. Please make sure that you completely remove all Assets of App Center SDK, remove project build, clean the cache and after these steps reinstall new packages via App Center Unity Editor Extensions or manually.

**Comment by IgorGalimski** [comment]
@AnastasiaKubova 
Understood. But could you please renaming this script as a solution? It might save a lot of time of other developers

**Comment by AnastasiaKubova** [comment]
Sure, I will mention in my comment with the reproducing steps that it is a workaround for this issue.

**Comment by IgorGalimski** [comment]
Thank you!

**Comment by AnastasiaKubova** [comment]
Thanks for using App Center.
