### ISSUE TITLE
ARR Module is not unlinked correctly.

### ISSUE THREAD

**Issue by marcinwalus** [Microsoft/AppCenter-SDK-Unity#497]
### **Description**

I'm building my Unity project to Android platform. Project needs to be build twice to link/unlink module correctly. I suspect the reason is that linking is done in "PostprocessBuild" and not in "PreprocessBuild".

This is a problem in scenario when project is build in CI. In my case I want to disable Distribute module in "release" builds and I'm modifying settings in "AppCenterSettings.asset" file. Then build player from script. And the problem is that Distribute module is still linked after first build and I need to build player twice to workaround this. 

### **Repro Steps**

1. Build Android project with Distribute module turned on -> "Export project" in Build Settings -> "unityLibrary\build.gradle" file contains "appcenter-distribute-release" linked what is as expected.
2. Disable "Distribute" module in "AppCenterSettings.asset" in Unity.
3. Build again project for Android ->  "Export project" in Build Settings -> "unityLibrary\build.gradle" file **still** contains "appcenter-distribute-release" linked but should not.
4. Build again project for Android -> "Export project" in Build Settings -> "unityLibrary\build.gradle" file **does not** contain "appcenter-distribute-release".

### **Details**

1. Which SDK version are you using?
    - 4.2.0
2. Which platform did you experience the issue on?
    - Project is build for Android; Unity 2020.3.13 on macOS 11.4
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - N/A
4. What third party plugins are you using?
    - N/A
5. Please enable verbose logging for your app using **Initial Log Level** setting and include the logs here:
    - N/A
6. Please share a screenshot of App Center Settings (without app secrets)
    - N/A
7. Please share a screenshot of Build and Player Settings.

![Distribute01](https://user-images.githubusercontent.com/1926917/125805011-325c21e9-ee5d-4adb-9021-576ae2d0aac4.png)
![Distribute02](https://user-images.githubusercontent.com/1926917/125805034-21a1bbdb-58cc-4125-9b7a-e4a84c9682f0.png)
![Distribute03](https://user-images.githubusercontent.com/1926917/125805053-bca9e36e-7a99-4b8c-a132-ec2c3a2c96a7.png)

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us! 
I was able to reproduce your issue. I will label this issue as a bug.

**Comment by aleksandr-dorofeev** [comment]
Hey, @marcinwalus !
We've included fixes in the latest SDK release for this. I'm closing the issue but please reopen if you run into this again.
