### ISSUE TITLE
iOS app gets into a state where it continuously crashes on app launch since iOS 15.0.x

### ISSUE THREAD

**Issue by mrwellmann** [Microsoft/AppCenter-SDK-Unity#503]
### **Description**
We have an issue that our iOS app gets into a state where it continuously crashes on app launch since iOS 15.0.x. I have originally posted this on the Azure Spatial Anchors git hub as we thought it cam from ASA https://github.com/Azure/azure-spatial-anchors-samples/issues/310.

There are no some hints https://github.com/Azure/azure-spatial-anchors-samples/issues/310#issuecomment-949476223 that it might be connected to the crash reports generated by App Center.

Is there already a know issue with iOS 15.0.x and App Center?
Is there an easy way to make App Center send a crash report after an app starts again to test this behavior?

**Comment by aleksandr-dorofeev** [comment]
Hi, @mrwellmann!
Thanks for getting in touch with us!
Could you please share the [verbose logs](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/unity#adjust-the-log-level)?

**Comment by mrwellmann** [comment]
Thanks for the quick response.

Can you please specify/correct me on how to aquire the logs. 
1. I set the App Center Behavior to Log Level Verbose
2. Build and Deploy a iOS Development Build to my iPhone
3. Try to reproduce the crash while connected to my mac
4. Copy the logs from the xCode Console

I just saw there is an option to delay the start of App Center https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/unity#delay-the-start-of-app-center. If App Center is actually the cause, this should postpone the crash. (If this setting also delays the forced App Center from the Azure Spatial Anchors SDK)

**Comment by aleksandr-dorofeev** [comment]
You are absolutely right , please follow these steps and send the logs. Without them, unfortunately, it is difficult to understand the problem.

**Comment by mrwellmann** [comment]
Thanks, I will not be able to do it this week as we do not have a clear reproducible test case and it is not happening on every crash. I will keep this thread up to date with my findings.

**Comment by aleksandr-dorofeev** [comment]
Okay, thank you for your response! At the moment I close this issue, as soon as any information will appear, you can open it again.
