### ISSUE TITLE
Android: AppCenterLoader: java.lang.ClassCastException when used with Intune Company Portal

### ISSUE THREAD

**Issue by JacekMSFT** [Microsoft/AppCenter-SDK-Unity#505]
### **Description**

We have a Unity app that is using AppCenter extension. We are also integrating with Intune SDK. As part of Intune SDK, application DefaultApplication extends MAMApplication. It looks like however that **com.microsoft.appcenter.loader.AppCenterLoader** is making some assumptions about the type of the Application and is crashing our app.

### **Repro Steps**

Please list the steps used to reproduce your issue.
1. Download and install https://play.google.com/store/apps/details?id=com.microsoft.ramobile
2. Download and install https://play.google.com/store/apps/details?id=com.microsoft.windowsintune.companyportal
3. Launch the app

Current:
Crash, see log cat

Expected: 
No crash

When Intune is not installed, application is not crashing.

Stacktrace:
--------- beginning of crash
12-01 20:07:25.400 18969 18969 E AndroidRuntime: FATAL EXCEPTION: main
12-01 20:07:25.400 18969 18969 E AndroidRuntime: Process: com.microsoft.ramobile, PID: 18969
12-01 20:07:25.400 18969 18969 E AndroidRuntime: java.lang.RuntimeException: Unable to get provider **com.microsoft.appcenter.loader.AppCenterLoader: java.lang**.**ClassCastException**: com.microsoft.intune.mam.client.content.MAMContext cannot be cast to android.app.Application
12-01 20:07:25.400 18969 18969 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:6770)
12-01 20:07:25.400 18969 18969 E AndroidRuntime: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6312)
12-01 20:07:25.400 18969 18969 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6227)
12-01 20:07:25.400 18969 18969 E AndroidRuntime: 	at android.app.ActivityThread.access$1200(ActivityThread.java:238)
12-01 20:07:25.400 18969 18969 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1787)
12-01 20:07:25.400 18969 18969 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-01 20:07:25.400 18969 18969 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
12-01 20:07:25.400 18969 18969 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7073)
12-01 20:07:25.400 18969 18969 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-01 20:07:25.400 18969 18969 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
12-01 20:07:25.400 18969 18969 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
12-01 20:07:25.400 18969 18969 E AndroidRuntime: Caused by: java.lang.ClassCastException: com.microsoft.intune.mam.client.content.MAMContext cannot be cast to android.app.Application
12-01 20:07:25.400 18969 18969 E AndroidRuntime: 	at com.microsoft.appcenter.loader.AppCenterLoader.onCreate(AppCenterLoader.java:166)
12-01 20:07:25.400 18969 18969 E AndroidRuntime: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1940)
12-01 20:07:25.400 18969 18969 E AndroidRuntime: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1915)
12-01 20:07:25.400 18969 18969 E AndroidRuntime: 	at com.microsoft.intune.mam.client.content.MAMContentProvider.attachInfoReal(MAMContentProvider.java:174)
12-01 20:07:25.400 18969 18969 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-01 20:07:25.400 18969 18969 E AndroidRuntime: 	at com.microsoft.intune.mam.InterProxy$InterInvocationHandler.invoke(InterProxy.java:88)
12-01 20:07:25.400 18969 18969 E AndroidRuntime: 	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
12-01 20:07:25.400 18969 18969 E AndroidRuntime: 	at $Proxy8.attachInfoReal(Unknown Source)
12-01 20:07:25.400 18969 18969 E AndroidRuntime: 	at com.microsoft.intune.mam.client.content.ContentProviderBehaviorImpl.attachInfoMAM(ContentProviderBehaviorImpl.java:429)
12-01 20:07:25.400 18969 18969 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-01 20:07:25.400 18969 18969 E AndroidRuntime: 	at com.microsoft.intune.mam.InterProxy$InterInvocationHandler.invoke(InterProxy.java:88)
12-01 20:07:25.400 18969 18969 E AndroidRuntime: 	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
12-01 20:07:25.400 18969 18969 E AndroidRuntime: 	at $Proxy7.attachInfoMAM(Unknown Source)
12-01 20:07:25.400 18969 18969 E AndroidRuntime: 	at com.microsoft.intune.mam.client.content.MAMContentProvider.attachInfoMAM(MAMContentProvider.java:326)
12-01 20:07:25.400 18969 18969 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-01 20:07:25.400 18969 18969 E AndroidRuntime: 	at com.microsoft.intune.mam.InterProxy$InterInvocationHandler.invoke(InterProxy.java:88)
12-01 20:07:25.400 18969 18969 E AndroidRuntime: 	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
12-01 20:07:25.400 18969 18969 E AndroidRuntime: 	at $Proxy8.attachInfoMAM(Unknown Source)
12-01 20:07:25.400 18969 18969 E AndroidRuntime: 	at com.microsoft.intune.mam.client.content.ContentProviderBehaviorImpl.attachInfo(ContentProviderBehaviorImpl.java:162)
12-01 20:07:25.400 18969 18969 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-01 20:07:25.400 18969 18969 E AndroidRuntime: 	at com.microsoft.intune.mam.InterProxy$InterInvocationHandler.invoke(InterProxy.java:88)
12-01 20:07:25.400 18969 18969 E AndroidRuntime: 	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
12-01 20:07:25.400 18969 18969 E AndroidRuntime: 	at $Proxy7.attachInfo(Unknown Source)
12-01 20:07:25.400 18969 18969 E AndroidRuntime: 	at com.microsoft.intune.mam.client.content.MAMContentProvider.attachInfo(MAMContentProvider.java:53)
12-01 20:07:25.400 18969 18969 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:6765)
12-01 20:07:25.400 18969 18969 E AndroidRuntime: 	... 10 more

### **Details**

1. Which SDK version are you using?
    - 3.3.1
2. Which platform did you experience the issue on?
    - All Androids
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Google Pixel 2 XL, Galaxy Note 
4. What third party plugins are you using?
Intune SDK - https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-get-started
5. Please enable verbose logging for your app using **Initial Log Level** setting and include the logs here:
6. Please share a screenshot of App Center Settings (without app secrets)
7. Please share a screenshot of Build and Player Settings.

**Comment by AnatolyPristensky** [comment]
Hello @JacekMSFT, thank you for getting in touch with us!
I see that you are using App Center SDK 3.3.1, and the latest version is [4.3.0](https://github.com/microsoft/appcenter-sdk-unity/releases/tag/4.3.0).
Could you please try to update App Center to the latest version and check if this issue still persist?
Also could you please clarify on what App Center modules you are using?

**Comment by JacekMSFT** [comment]
@AnatolyPristensky thank you replying. 

We tried to migrate to the latest 4.3.0 last night however it didn't solve the problem.

We are using two modules, Analytics and Crashes.

**Comment by DmitriyKirakosyan** [comment]
I'm closing this issue as the fix is already released.
