### ISSUE TITLE
Android SharedPreferences - NullPointerException

### ISSUE THREAD

**Issue by brzGatsu** [Microsoft/AppCenter-SDK-Unity#512]
### **Description**

My game gets a NullPointerException caused by the AppCenter SDK when it initializes.

### **Repro Steps**

- Build apk and push to device
- Start apk
- Notice error log

### **Details**

1. Which SDK version are you using?
    - 4.4.0
    - Unity 2020.3.26
2. Which platform did you experience the issue on?
    - ARMv7, API 28, Android 9
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Moto G6, physical device
4. Callstack:

AndroidJavaException: java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.content.SharedPreferences.getBoolean(java.lang.String, boolean)' on a null object reference

java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.content.SharedPreferences.getBoolean(java.lang.String, boolean)' on a null object reference
com.microsoft.appcenter.utils.storage.SharedPreferencesManager.getBoolean(SharedPreferencesManager.java:68)
com.microsoft.appcenter.AbstractAppCenterService.isInstanceEnabled(AbstractAppCenterService.java:136)
com.microsoft.appcenter.distribute.Distribute.registerReceiver(Distribute.java:612)
com.microsoft.appcenter.distribute.Distribute.onActivityResumed(Distribute.java:550)
com.unity3d.player.UnityPlayer.nativeRender(Native Method)
com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
android.os.Handler.dispatchMessage(Handler.java:102)
android.os.Looper.loop(Looper.java:193)
com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
UnityEngine.AndroidJNISafe.CheckException () (at <00000000000000000000000000000000>:0)
UnityEngine.AndroidJavaObject._Call (System.String methodName, System.Object[] args) (at <00000000000000000000000000000000>:0)
System.Action.Invoke () (at <00000000000000000000000000000000>:0)

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us! Could you please share the [verbose logs](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/unity#adjust-the-log-level)?

**Comment by brzGatsu** [comment]
I dont feel comfortable sharing these but I didn't see any log from AppCenter whatsoever, even with the verbose setting. One thing I forgot: the app seems to run fine even with this error, it doesn't crash.

**Comment by AnastasiaKubova** [comment]
Did you get this error before? If it's convenient for you, you can send your logs by email or open [support ticket](https://docs.microsoft.com/en-us/appcenter/general/support-center#contact-us) on the App Center portal.

**Comment by brzGatsu** [comment]
I didnt get this error before. I upgraded from SDK 3.3.1 to 4.4.0 and it appeared.

**Comment by aleksandr-dorofeev** [comment]
Hi @brzGatsu
For more effective assistance we need to know what you use in App Center.
If you can't share the [verbose logs](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/unity#adjust-the-log-level) here, you can send your logs by email or open [support ticket](https://docs.microsoft.com/en-us/appcenter/general/support-center#contact-us) on the App Center portal.
[14:28] Dmitry Kirakosian (Akvelon INC)
Could you tell what settings do you use in the App Center Behaviour? Screenshot or text.

**Comment by aleksandr-dorofeev** [comment]
Hi @brzGatsu
For more effective assistance we need to know what you use in App Center.
If you can't share the [verbose logs](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/unity#adjust-the-log-level) here, you can send your logs by email or open [support ticket](https://docs.microsoft.com/en-us/appcenter/general/support-center#contact-us) on the App Center portal.
Could you tell what settings do you use in the App Center Behaviour? Screenshot or text.

**Comment by AnastasiaKubova** [comment]
We haven’t heard from you in a while so I’m closing this issue but feel free to reopen this issue if you have additional questions.

**Comment by brzGatsu** [comment]
@AnastasiaKubova it seems I do not have the permissions to repoen the issue.

@aleksandr-dorofeev, thanks for looking at this.

Here are my settings:

![appcenter](https://user-images.githubusercontent.com/1515649/151828885-1a77ef8d-da96-4196-a748-e75cc1556ff7.png)

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for sharing additional info! I'm trying to reproduce this issue, but for me still all work well. Have you a chance to share verbose logs?

**Comment by DmitriyKirakosyan** [comment]
We haven't heard from you for a while, so I'm closing this issue again. Please provide requested information if you are still interested in this issue.
