### ISSUE TITLE
Guidance needed for EUDB Schrems Compliance 

### ISSUE THREAD

**Issue by henrli** [Microsoft/AppCenter-SDK-Unity#515]
Hello, 

My team has an app using AppCenter SDK (Unity) and we are trying to bring the app into compliance with the EUDB regulations. You can read more about the efforts here 
https://techcommunity.microsoft.com/t5/security-compliance-and-identity/eu-data-boundary-for-the-microsoft-cloud-frequently-asked/ba-p/2329098
https://blogs.microsoft.com/eupolicy/2021/12/16/eu-data-boundary-for-the-microsoft-cloud-a-progress-report/

The essence of the regulation is that telemetry emitted by users in the EU region must be collected and processed in the EU data boundary. So we'll need to be able to set the collector endpoint URL 

Does your team have any official guidance/documentation on how to achieve this? I think we can't be the only team that is working to gain compliance. 

Also, we have noticed that the AppCenter class has a static function `SetLogUrl`. We are trying to test whether setting the endpoint on the Unity GameObject achieves the expected redirection (currently waiting for the telemetry to propagate into our Aria clusters). However, in practice, our usage might require the telemetry system to be restarted with the EU collector endpoint URL defined since we can only determine the user's region after the login process. The question is, whether the `SetLogUrl` function will automatically restart the telemetry system after a new URL is supplied? Maybe the system is such that the restart isn't required at all? We couldn't find clear indication/documentation on the expected behavior after using this function and want to get a better understanding. 

Thanks!

**Comment by DmitriyKirakosyan** [comment]
Hi @henrli , thank you for getting in touch with us!

I'll reach out to our PM team and get back to you with an update!

**Comment by wisdeom** [comment]
Thank you @henrli for opening this issue and reaching out. We do not recommend using SetLogUrl to redirect telemetry to your own managed server located in EU, and I don't believe this can help you achieve EUDB Schrems compliance. From what I know the action must be taken from our end. Also, redirecting telemetry could also bring more compliance and security issues from my point of view. 

I have to admit this ask is one of the frequently asked questions from our EU customers, yet realistically speaking data redundancy in the EU won't be achievable in the near future. I understand this can be a big headache, and I also feel frustrated as I'm saying so. Apologies for any convenience. 

If EUDB Schrems is critical to your business, another Microsoft solution such as Azure PlayFab Unity supports[ EU regions](https://docs.microsoft.com/en-us/gaming/playfab/features/multiplayer/networking/supported-azure-regions) in the meantime. Sorry once again.
