### ISSUE TITLE
Analytics installation package required

### ISSUE THREAD

**Issue by petrinordlund** [Microsoft/AppCenter-SDK-Unity#516]
### **Description**

The 4.4.0 release version seems to always require the Analytics package to installed as the AppCenterBehavior.cs file references it. We don't allow external analytics packages on our products. I was able to fix the issue by just commenting out the offending lines of code.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Install the Distribute package.
2. Install the Crashes package. Unity gives a compilation error about the Analytics package being missing.

### **Details**

1. Which SDK version are you using?
   4.4.0

**Comment by AnatolyPristensky** [comment]
Hello @ddes02!
Thank you for getting in touch with us. 
We've filed a bug on our internal dashboard, will update this thread once it's fixed.

**Comment by Decavoid** [comment]
`AppCenterStarter.m` doesn't compile without Analytics package:
```
Libraries/AppCenter/Plugins/iOS/Core/AppCenterStarter.m:119:6: error: use of undeclared identifier 'MSACAnalytics'
    [MSACAnalytics enableManualSessionTracker];
```

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to fix this bug in the next year, I'm closing the issue.
