### ISSUE TITLE
App Secrets for Dev & Prod apps?

### ISSUE THREAD

**Issue by BlueSpiritbox** [Microsoft/AppCenter-SDK-Unity#519]
Hello,

I was wondering if it's possible to add separate app secrets for different environments like dev and prod? We want to use App Center Analytics, but we don't want the analytics data from the development builds to be added to the analytics from the production builds.

I was thinking of adding multiple AppCenterBehavior components (one for dev and one for prod) and switch between them, but I can't add more than 1 AppCenterBehavior component.

Is this possible? And what's the best way to achieve this?

I'm using:
- Unity 2020.3.23f1
- AppCenterAnalytics v4.4.0

Thanks!
/Elwin

**Comment by AnatolyPristensky** [comment]
Hello @BlueSpiritbox 
thanks for your feedback.
As far as I understand this behaviour isn't supported. 
Also, as you can see in our [roadmap](https://github.com/microsoft/appcenter/wiki/Roadmap) we will prioritize improving reliability and performance for the service through 2022.
This means new feature work will be significantly reduced.
I'm not sure that we could take this item in work in nearest future.

**Comment by BlueSpiritbox** [comment]
> Hello @BlueSpiritbox thanks for your feedback. As far as I understand this behaviour isn't supported. Also, as you can see in our [roadmap](https://github.com/microsoft/appcenter/wiki/Roadmap) we will prioritize improving reliability and performance for the service through 2022. This means new feature work will be significantly reduced. I'm not sure that we could take this item in work in nearest future.

Thank you for your reply and the info. I was thinking about writing a script to switch between dev and prod appcenter secrets based on the build type, but according to the documentation "It's not recommended to embed your App Secret in source code.". How would you suggest on doing so? Wouldn't the app secret entered in the AppCenterBehavior component be embedded anyway or?

**Comment by AnatolyPristensky** [comment]
@BlueSpiritbox, yes, it's not recommended to store AppSecrets in code, so you can create a config file with AppSecrets that won't be stored in the repository but on the CI, or you can use environment variables.
