### ISSUE TITLE
No analytics data on UWP in App Center

### ISSUE THREAD

**Issue by hippogamesunity** [Microsoft/AppCenter-SDK-Unity#527]
### **Description**

Hi! I'm using the latest asset version with Unity 2021 LTS, but I don't see any analytics data on UWP in App Center. I don't have any errors in logs when sending events. It works fine for Android and iOS BTW.

My app is published on MS Store https://apps.microsoft.com/store/detail/pixel-studio/9P7XS7VH1R3J
My App Center page: https://appcenter.ms/users/hippogamesunity-gmail.com/apps/Pixel-Studio-Mictosoft-Store/analytics/overview

### **Repro Steps**

1. Import analytics package
2. Send events
3. Check analytics in App Center (empty)

### **Details**

1. Which SDK version are you using?
    - 4.4.0
2. Which platform did you experience the issue on?
    - UWP
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - x64/x32 Windows 10/11

**Comment by hippogamesunity** [comment]
I also had to apply this workaround to build it on UWP https://github.com/microsoft/appcenter-sdk-unity/issues/513

**Comment by AnatolyPristensky** [comment]
Hello @hippogamesunity,
Could you please switch to LogLevel `verbose` and share logs?

**Comment by hippogamesunity** [comment]
> Hello @hippogamesunity, Could you please switch to LogLevel `verbose` and share logs?

Hi, sure [Logs.txt](https://github.com/microsoft/appcenter-sdk-unity/files/9882971/Logs.txt)

**Comment by AnatolyPristensky** [comment]
@hippogamesunity I see a lot of errors in logs:

```
Exception thrown at 0x00007FFB7DC7FB0C (KernelBase.dll) in Pixel Studio.exe: 0x00000005: Access is denied.
onecoreuap\net\netprofiles\winrt\networkinformation\lib\handlemanager.cpp(432)\Windows.Networking.Connectivity.dll!00007FFB55BE0086: (caller: 00007FFB55BB1EA4) LogHr(6) tid(3a90) 80070005 Access is denied.
'Pixel Studio.exe' (Win32): Loaded 'C:\Windows\System32\Windows.Networking.HostName.dll'.
```

And 

```
 23:34:37.881 [AppCenter] VERBOSE: HTTP response status=400 (BadRequest) payload={"status":"FailedToDeserialize","validDiagnosticsIds":[],"throttledDiagnosticsIds":[],"correlationId":"1fcc1f0c-078e-4234-b6f0-0fe1fb47005f"}
```

Could it be related to issues with your local environment? Also can you reproduce this issue on an empty project?

**Comment by hippogamesunity** [comment]
I'll try. I'm not a UWP expert unfortunately. Maybe your asset needs some Permissions/Capabilities?
I've checked only 2 Capabilities needed for other plugins:
![image](https://user-images.githubusercontent.com/7318172/198557396-bac00788-712a-4e93-98a7-fd4698c48a66.png)

**Comment by hippogamesunity** [comment]
My app is released on MS Store, so it's definitely not my local environment as there are no events at all.

**Comment by AnatolyPristensky** [comment]
@hippogamesunity, please try to reproduce it on empty project and share your results. 
We will also try to reproduce it on our side.

**Comment by hippogamesunity** [comment]
Right, give me some time.

**Comment by hippogamesunity** [comment]
@AnatolyPristensky it doesn't work for empty project
1. Install Unity 2021.3.12
2. Create new 2D project
3. Install AppCenterAnalytics-v4.4.0.unitypackage
4. Create AppCenterBehaviour, set UWP ID
5. Comment FixIl2CppLogging(pathToBuiltProject); as described here [FixIl2CppLogging(pathToBuiltProject);](https://github.com/microsoft/appcenter-sdk-unity/issues/513) (you can't build without this step)
6. Open in Visual Studio & Run

**Comment by aleksandr-dorofeev** [comment]
Hello @hippogamesunity
Sorry for the long wait time. Unfortunately, we were unable to reproduce the error following the steps you described. Which way do you add packages to the application? Using an extension or manually?
Also, could you share an sample empty AppCenter application that reproduced the error?

**Comment by aleksandr-dorofeev** [comment]
We haven't heard from you for a while, so I'm closing this issue. Please feel free to reopen this if you have any questions or if you can provide a sample app.
