### ISSUE TITLE
Please make AppCenter a Github package

### ISSUE THREAD

**Issue by Tommigun1980** [Microsoft/AppCenter-SDK-Unity#531]
**Is your feature request related to a problem? Please describe.**
AppCenter is one of a few somewhat widely used services that still don't have a Github package.

**Describe the solution you'd like**
Please consider adding a package.json and asmdefs to the package, and make sure that the local writes work properly. Packaging up AppCenter seems very doable and would make developers lives easier.

**Describe alternatives you've considered**

**Additional context**
It is an expectation that plugins are served as Github packages. AppCenter should conform.

**Comment by aleksandr-dorofeev** [comment]
Hello @Tommigun1980
Thanks for the feature request! Unfortunately we don't have an ETA, but contribution is always welcome :)

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
