### ISSUE TITLE
Has AppCenter been sunset?

### ISSUE THREAD

**Issue by Tommigun1980** [Microsoft/AppCenter-SDK-Unity#532]
There seems to be next to none activity in AppCenter. Has it been axed? If so, please be transparent about this so we can look into alternatives.

**Comment by SyaoranChang** [comment]
Hi,

Looks like Microsoft has officially given up on AppCenter.
Visual Studio App Center Retirement
https://learn.microsoft.com/en-us/appcenter/retirement
