### ISSUE TITLE
[iOS] Distribute service hasn't been started

### ISSUE THREAD

**Issue by marcinwalus** [Microsoft/AppCenter-SDK-Unity#533]
### **Description**

Distribute is no longer working on iOS (and Android). Dialog about new version available upon application startup it not displayed.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Build app in Unity (for iOS or Android) - configure Distribute module
2. Publish an app to AppCenter
3. Run "previous" version of and app on device: no dialog about new version of an app is displayed.

### **Details**

1. Which SDK version are you using?
- 4.4.0
- Unity 2022.2.18
2. Which platform did you experience the issue on?
- iOS 16.4.1
3. What device version did you see this error on?  Were you using an emulator or a physical device?
- iPhone 13 Pro Max
4. What third party plugins are you using?
- n/a
6. Please enable verbose logging for your app using **Initial Log Level** setting and include the logs here:

I can see in the logs but have no idea why this happens:
- Distribute service hasn't been started. You need to call [MSACAppCenter start:YOUR_APP_SECRET withServices:LIST_OF_SERVICES] first.

7. Please share a screenshot of App Center Settings (without app secrets)
- AppCenterSettings.asset file is modified from build script and asset database is correctly updated after modification.

<img width="445" alt="Screenshot 2023-05-07 at 15 46 29" src="https://user-images.githubusercontent.com/1926917/236681590-7263fc4d-a4f4-4f3e-9987-a529681d48c1.png">
<img width="1583" alt="Screenshot 2023-05-07 at 15 26 24" src="https://user-images.githubusercontent.com/1926917/236681610-3c2aee2c-b0fd-4d2c-86eb-84550d78da06.png">

[log.txt](https://github.com/microsoft/appcenter-sdk-unity/files/11415167/log.txt)

**Comment by AnatolyPristensky** [comment]
Hello @marcinwalus, please make sure that your AppCenter configuration is correct according [App Center Distribute – Unity](https://learn.microsoft.com/en-us/appcenter/sdk/distribute/unity) and [Get Started with Unity](https://learn.microsoft.com/en-us/appcenter/sdk/getting-started/unity) also it would be helpful if you provide more information on how AppCenter is configured in your case.

**Comment by marcinwalus** [comment]
Hi.
@AnatolyPristensky thank for your suggestions. Yes, I'm trying to check if my configuration is correct. I already had this feature working correctly - it stopped working some time ago and I think/suspect that it is connected with upgrading to 4.4.0 or updating Unity version from 2021 to 2022.

I have this settings in Unity
![Screenshot 2023-05-08 at 14 56 29](https://user-images.githubusercontent.com/1926917/236832514-1a9fad06-7bb7-44fd-8479-08ab50ebbe3c.png)


Now, when I look at `AppCenterStarter.startAppCenter` method I do have `#define APPCENTER_UNITY_USE_DISTRIBUTE` and `#define APPCENTER_UNITY_USE_ANALYTICS` at the very top of the file.
I spot that there is no code in this method which adds MSACDistribute to classes dictionary - same way as MSACAnalytics is added in line 89.
Is this the case that when having distribute module enabled MSACDistribute class should be also in classes dictionary?  Then start method will be called with two entries in my case
```
[MSACAppCenter start:customAppSecretValue withServices:classes];
```

![Screenshot 2023-05-08 at 14 58 32](https://user-images.githubusercontent.com/1926917/236833524-e5a12b37-468c-46e5-934a-30f2529b4e5e.png)
![Screenshot 2023-05-08 at 14 59 17](https://user-images.githubusercontent.com/1926917/236833549-92b06d97-2092-4fcc-910a-13d59410b16d.png)

This is my AppCenterStarter class
[AppCenterStarter.m.txt](https://github.com/microsoft/appcenter-sdk-unity/files/11421417/AppCenterStarter.m.txt)

**Comment by marcinwalus** [comment]
Hi.
I fixed this issue by adding `AppCenterBehaviorAdvanced` to my AppCenter game object on Main scene and set `StartAndroidNativeSDKFromAppCenterBehavior` and `StartIOSNativeSDKFromAppCenterBehavior` flags to `true`.

![Screenshot 2023-05-10 at 07 43 29](https://github.com/microsoft/appcenter-sdk-unity/assets/1926917/3558bbd0-e657-4e2f-bcc8-5168b9d29ff8)

**Comment by MikhailSuendukov** [comment]
Hi and thank you very much for sharing your solution here. In that case, I close this issue, if you have any other questions, feel free to reopen it.
